extends Node
## Music and sound.
##
## Music is vertical, not horizontal. A cue is not one file: it is six stems
## that all start on the same sample, and `intensity` decides how many of them
## you can hear. Nothing restarts when a fight begins -- the arrangement opens
## up. That is why the transition costs nothing and cannot land you in the
## wrong place.
##
## THE SECOND EDITION, 2026-09-12. The first soundtrack was thirteen cues built
## from one whistled five-note phrase, tempo-locked at 142 BPM, each cue doing
## one thing to the motif. Jon played the finished game and called it hollow,
## sickly, a slow funeral, not musical at all. The fault was the FORM rather
## than the details: a four-bar loop with a tune over it is a song, and this
## game wanted a score.
##
## So there is no tempo now, and no bar lines. Every cue is a low F pedal that
## never moves, harmony that changes about once a minute above it, texture that
## opens over twenty seconds, and one five-note theme that arrives three times a
## loop as an event rather than a layer. Cues differ by how dark they are, which
## harmonic areas they use, and whether the theme states its aching form or its
## answer. Crossfading between two of them still works because they share the
## pedal -- the same trick the old set used, for the same reason.
##
## The rulings that shape it, and the mistakes that produced them, are in
## `audio/space.py`. The old composition notes in `docs/audio/` describe the
## first edition and are kept as its record.

const MUSIC_DIR := "res://assets/audio/music/%s/%s.ogg"
const SFX_PATH := "res://assets/audio/sfx/%s.wav"

## Layer tables, straight from THEME_NOTES §5 and DREAD_NOTES §4. A stem joins
## at its intensity and never leaves, so raising intensity only ever adds.
## Cues that are ONE FINISHED PIECE rather than a stack of stems.
##
## Everything else in here is generated by `audio/*.py` and shipped as separate
## layers so a cue can climb a ladder — that is the whole design, and it is why
## `MUSIC_DIR` assumes a stem per rung. A track somebody wrote and mixed has no
## rungs to climb: it is already arranged, and cutting it into layers to fit the
## system would be undoing the arrangement to fit a mechanism it does not need.
##
## So a cue named here loads that one file and behaves as a single-rung cue.
## Everything downstream — the crossfade, the DEEP swap, the ducking — works on
## a cue's gain and never looked inside it.
## Empty since the lobby got its own cue: "Five Ways Home" was written from
## measurements of the placeholder track this table carried, and shipped as
## proper stems.  The mechanism stays for the next time somebody has one
## finished file and no reason to cut it up.
const TRACKS := {}

## The one stem a TRACKS cue has. Named rather than empty so the mixer's
## per-stem dictionaries do not need a special case.
const WHOLE := &"song"

const CUES := {
	## THREE FAMILIES, NOT ONE FORM, and the family is why a rung means what it
	## means.
	##
	## The first pass at this edition gave all thirteen cues the same six voices
	## and varied five numbers between them. Jon's verdict was "these all sound
	## the same", and he was right: that is variation by dial rather than by
	## composition. He also said the combat cue did not feel like combat, which is
	## the same fault from the other end -- "no tempo, no bar lines" is correct
	## for a starchart and wrong for a fight.
	##
	##   STILL    drone, almost no events. The archive, the end of a run.
	##   DRIFT    drone plus the theme as an event. Chart, sector, station.
	##   DRIVE    an ostinato with a pulse in it, harmony moving four times as
	##            fast, strikes landing ON the bar. Combat and bosses.
	##
	## DRIVE IS NOT A DRUM KIT. DREAD_NOTES rules that rhythm is a pulse and not
	## a groove, and there is no kick, snare or backbeat anywhere: what drives is
	## a low ostinato and filtered stabs, with pitch and the filter doing the work
	## a kit would do.
	##
	## The rungs read the same way in every family even though the stems differ:
	## rung 0 is the place, rung 1 is the place noticing you, rung 2 is the theme,
	## rung 3 is the cue at full. `play_cue` clamps, so STATES asking for rung 4
	## lands on rung 3.
	##
	## THEY ARE NOT ALL IN F any more. One pedal for thirteen cues was most of why
	## they blurred. The five that crossfade through DEEP -- theme, dread, burn,
	## boss, business -- still share F, because a shared pedal is what makes that
	## swap read as the place turning. The other eight are in five other keys.
	##
	## Rendered by `tkg/audio/space.py`, which carries the rulings and the
	## mistakes that produced them.
	&"first_light": [   ## drift
		[&"pedal", &"organ"],
		[&"motion", &"metal"],
		[&"theme"],
		[&"upper"],
	],
	&"shells": [   ## drift
		[&"pedal", &"organ"],
		[&"motion", &"metal"],
		[&"theme"],
		[&"upper"],
	],
	&"warm": [   ## drift
		[&"pedal", &"organ"],
		[&"motion", &"metal"],
		[&"theme"],
		[&"upper"],
	],
	&"home": [   ## drift
		[&"pedal", &"organ"],
		[&"motion", &"metal"],
		[&"theme"],
		[&"upper"],
	],
	&"perpetuity": [   ## still
		[&"pedal", &"organ"],
		[&"breath", &"metal"],
		[&"theme"],
		[&"upper"],
	],
	&"nofault": [   ## still
		[&"pedal", &"organ"],
		[&"breath", &"metal"],
		[&"theme"],
		[&"upper"],
	],
	&"core": [   ## drift
		[&"pedal", &"organ"],
		[&"motion", &"metal"],
		[&"theme"],
		[&"upper"],
	],
	&"fauna": [   ## drift
		[&"pedal", &"organ"],
		[&"motion", &"metal"],
		[&"theme"],
		[&"upper"],
	],
	&"theme": [   ## drift
		[&"pedal", &"organ"],
		[&"motion", &"metal"],
		[&"theme"],
		[&"upper"],
	],
	&"business": [   ## drift
		[&"pedal", &"organ"],
		[&"motion", &"metal"],
		[&"theme"],
		[&"upper"],
	],
	&"dread": [   ## still
		[&"pedal", &"organ"],
		[&"breath", &"metal"],
		[&"theme"],
		[&"upper"],
	],
	&"burn": [   ## drive
		[&"pedal", &"organ"],
		[&"pulse", &"metal"],
		[&"theme"],
		[&"stab"],
	],
	&"boss": [   ## drive
		[&"pedal", &"organ"],
		[&"pulse", &"metal"],
		[&"theme"],
		[&"stab"],
	],
}

## Where a screen sits on the ladder. Router names the state; this is the only
## table that decides what it sounds like, so retuning the whole game's music
## pacing is a one-file edit.
## The root each cue is written on. The mixer needs this for one decision only:
## whether two cues may be heard AT THE SAME TIME.
##
## The second edition put thirteen cues on one pedal, so any cue could be
## crossfaded into any other and the overlap was consonant by construction. The
## third edition is thirteen independent pieces in nine keys at thirteen tempos,
## and nothing was done about the crossfade -- so walking ship, sector, chart,
## archive played B flat major over F minor over G minor over E flat, two at a
## time, for 2.2 seconds each. Jon's verdict was that it REALLY was not working,
## and it was not: that is four bitonal collisions in four screen changes.
const ROOT := {
	&"first_light": &"C", &"theme": &"F", &"shells": &"G", &"warm": &"Bb",
	&"home": &"D", &"core": &"A", &"fauna": &"E", &"business": &"F",
	&"dread": &"F", &"perpetuity": &"Eb", &"nofault": &"B",
	&"burn": &"F", &"boss": &"F",
}

const STATES := {
	## THE TITLE AND THE SECTOR ARE THE SAME PIECE AT TWO DENSITIES, and that is
	## the point rather than an economy. "The Long Way Home" is the best thing in
	## the soundtrack and it spent a while as the sector cue only, for a reason
	## that does not survive being said out loud: F minor is REQUIRED of the DEEP
	## crossfade group, this piece was already in F minor, so it got filed where
	## the constraint was. That is an engineering convenience deciding where the
	## best material goes, which is backwards -- the title screen has no key
	## requirement at all.
	##
	## The title takes rung 3, the whole arrangement, because it is the one place
	## somebody sits and listens rather than plays. The sector takes rung 2, the
	## same piece without its counter-line. So arriving in a sector is the title
	## screen finishing its sentence more quietly, which is a thing a soundtrack
	## can do exactly once and only if it plans to.
	##
	## The cost, and it is real: this is now the most-heard music in the game by
	## a wide margin. If it wears out, that is the failure to watch for, and the
	## fix is one line here -- "warm" took this slot before and can take it back.
	##
	## "Five Ways Home" keeps the gameover-adjacent duties it was written for
	## and stays reachable if a screen asks.
	&"menu":     [&"theme", 3],
	## THE TITLE, THE LOBBY AND SHIP SELECTION ARE ONE MUSICAL PLACE. Everything
	## before you launch is the same moment, so it is the same piece at the same
	## rung and crossing between those screens does not touch the music at all.
	&"lobby":    [&"theme", 3],
	## The archive reached from the launcher is a PLACE: you are not standing in
	## a sector with a panel open, you are sitting with the records. Reached
	## mid-run it is a panel and changes nothing, which is why there are two.
	&"records":  [&"perpetuity", 2],
	&"chart":    [&"shells", 2],
	&"ship":     [&"warm", 1],
	&"station":  [&"warm", 2],
	&"sector":   [&"theme", 2],
	&"event":    [&"business", 2],
	&"combat":   [&"burn", 4],
	&"boss":     [&"boss", 4],
	&"gameover": [&"nofault", 2],
	&"archive":  [&"perpetuity", 2],
}

## Deep space swaps a cue for its darker counterpart at the same rung. Both
## pairs share a common F pedal and an exact tempo lock and differ by one note
## of the motif, so this reads as the *place* turning rather than as the music
## changing. DREAD_NOTES §5, "sector transition".
const DEEP := {
	&"theme": &"dread",
	&"burn": &"boss",
	&"business": &"dread",
}
## States the swap applies to. A station or the star chart sounds the same
## wherever you are; a place you are standing in does not.
const DEEP_STATES: Array[StringName] = [&"sector", &"combat", &"event"]
## Deep space never unlocks a cue's top rung. On "Poisoned Ground" that rung is
## the theme and the dread cue stated simultaneously, which is the boss reveal
## — so a danger-10 skirmish must not spend it first.
const DEEP_MAX := 3

## Danger at which a sector stops using the main theme and switches to the
## dread cue. The galaxy runs 1-10 and gets worse coreward, so this is the
## point where the soundtrack admits it.
const DREAD_DANGER := 8

const FADE := 1.4          ## seconds to bring a layer in or out
const CROSSFADE := 2.2     ## seconds to swap cues that share a root
## Seconds to fade out, and then in, when the two cues do NOT share a root.
## They never sound together, so there is no overlap to be dissonant. Faster
## than a crossfade because a gap you are waiting through is worse than a cut.
const SWITCH := 0.8
const OFF_DB := -60.0      ## a stem that is "off" is silent, not stopped
const SFX_VOICES := 14
## Fraction of heat capacity that counts as "running hot".
const HEAT_WARN_AT := 0.8

var master_volume: float = 0.9
var music_volume: float = 0.7
var sfx_volume: float = 0.9

var _stems: Dictionary = {}         ## cue -> {stem: AudioStreamPlayer}
var _gain: Dictionary = {}          ## cue -> float, whole-cue crossfade gain
var _gain_target: Dictionary = {}
var _cue: StringName = &""
var _intensity: int = 0
var _sfx: Array[AudioStreamPlayer] = []
var _sfx_next: int = 0
## One per voice, or null. A hush fades a voice out over a moment rather than
## stopping it dead, so the fade has to be KILLABLE: the round robin will come
## back to that voice long before a run is over, and a tween still dragging its
## volume down would take the next sound with it. See `hush` and `play`.
var _fade: Array[Tween] = []
var _cache: Dictionary = {}
var _variants: Dictionary = {}  ## name -> [name, name_2, ...] round robins
## FOR THE HARNESSES. While `taping` is on, every effect that actually plays --
## after rate limits and suppression have had their say, so nothing that was
## dropped -- is appended as [name, msec, db, pitch]. A film can then lay the
## sounds the game really made under its frames, rather than the ones the
## harness expected it to make. Off in play; nothing reads it but a harness.
var taping: bool = false
var tape: Array = []
var _last: Dictionary = {}          ## sfx name -> msec, for rate limiting
var _enabled: bool = true
var _last_credits: int = -1
var _last_cargo: int = -1
var _hot: bool = false
var _running: Dictionary = {}       ## cue -> bool, are its players rolling
var _pending: StringName = &""      ## cue waiting for silence before it starts
var _rate: float = CROSSFADE        ## seconds the current swap takes

# ---------------- the bed ----------------
## THERE IS NO ROOM TONE ANY MORE, and this note is the whole record of why.
##
## Three procedural loops used to run under everything — a reactor pedal riding
## heat, a hull that ticked and creaked, a distant radio near settled space.
## They are gone: Jon is sourcing ambience from ElevenLabs instead, which is a
## better tool for the job than a numpy script with opinions. `audio/ambience.py`
## and `assets/audio/ambience/` went with them; git has them if they are wanted.
##
## WHEN THEY COME BACK, they do not come back as cues. A cue is a composition
## with a bar line, a rung ladder and a crossfade that has to land on a beat.
## Room tone is continuous, seamless on its own length, and its level answers to
## the ship and the place rather than to a screen — so it wants its own player
## on the Music bus (scenery, not feedback: turning effects down should not take
## the room with it) and a fade measured in seconds, not in beats.

func _ready() -> void:
	# The balance sim boots the whole project so the autoloads exist. It runs
	# hundreds of combats with no window and no audio device, and loading 36 MB
	# of streams for it would be pure cost. Same guard Main.gd uses.
	if "sim" in OS.get_cmdline_user_args() or DisplayServer.get_name() == "headless":
		_enabled = false
		return
	process_mode = Node.PROCESS_MODE_ALWAYS      ## music keeps playing while paused
	load_settings()
	for i in SFX_VOICES:
		var p := AudioStreamPlayer.new()
		p.bus = &"SFX"
		add_child(p)
		_sfx.append(p)
		_fade.append(null)
	_connect_signals()


## Systems emit on Sig and never reach across scenes, so this is where the
## whole game's sound wiring lives — one place to read, one place to retune.
func _connect_signals() -> void:
	Sig.card_played.connect(_on_card_played)
	Sig.damage_dealt.connect(_on_damage)
	Sig.charge_fired.connect(func(_n: String) -> void: play(&"charge_fire"))
	Sig.overheated.connect(func(_b: int) -> void: play(&"overheat"))
	# NO STING WHEN A FIGHT STARTS. The music already tells you: combat moves the
	# cue to Hard Burn, which is 160 BPM of sixteenths against everything else in
	# the soundtrack. A sting on top of that is the score saying the same thing
	# twice, half a second apart, and the second one is louder.
	Sig.combat_ended.connect(_on_combat_ended)
	Sig.jumped.connect(func(_i: int) -> void: play(&"jump"))
	Sig.enemy_destroyed.connect(_on_enemy_destroyed)
	# Paperwork: the ledger stamps with the institutions' bare fifth, same
	# figure the score's stamp lanes carry.
	Sig.contracts_changed.connect(func() -> void:
		play(&"contract_stamp", 0.04, 250))
	Sig.archive_changed.connect(func() -> void:
		play(&"archive_found", 0.05, 400))
	# Every screen change is the same pressure door -- _swap() is the one
	# chokepoint, so the sound is right by construction, like the resource
	# poll. limit_ms soaks the double-swap paths (flee already stings, and
	# some routes swap twice on the way somewhere).
	Sig.screen_changed.connect(func() -> void:
		play(&"ui_tab", 0.04, 350))
	# ship_changed used to play module_install for EVERYTHING -- a sale
	# sounded like an installation. The desk actions now carry their own
	# sounds at the UI call sites (StationScreen/SectorScreen _on_action),
	# which also keeps bot pilots from clicking speakers they do not have.
	Sig.run_ended.connect(_on_run_ended)
	# Draw on turn start, not on hand_changed — the hand also changes when a
	# card leaves it, which put a draw sound on top of every card played.
	Sig.turn_started.connect(func(_t: int) -> void: play(&"card_draw", 0.10, 70))
	Sig.player_combat_state_changed.connect(_on_combat_state)
	Sig.resources_changed.connect(_poll_resources)
	Sig.screen_changed.connect(_poll_resources)
	Sig.run_started.connect(func() -> void:
		_last_credits = -1
		_last_cargo = -1
		_hot = false)

# ---------------- music ----------------

## Router calls this on every screen change. Unknown states are ignored rather
## than silencing the music, so a new screen is never a silent screen.
## A PANEL IS NOT A PLACE, AND ONLY A PLACE CHOOSES THE MUSIC.
##
## The ship, the star chart and the archive are things you OPEN while standing
## somewhere. The sector, the station, a fight, the title are where you ARE.
## Every one of them was naming a cue, so walking sector, ship, chart, archive
## changed the music four times in four clicks -- and no arrangement of fades
## makes that acceptable, because the problem is not how the music changes, it
## is that it changes at all. Opening your inventory is not an event in the
## fiction and should not be one in the score.
##
## So a panel asks for nothing. Whatever the place put on keeps playing, at the
## rung the place chose, and the panel does not even move the ladder -- Jon's
## words were "I don't really want the music to change when I change panels. At
## all." The STATES entry for a panel survives as a FALLBACK for the case where
## a panel is opened with nothing playing at all, which is how the archive
## sounds when it is reached from the lobby on a cold boot.
const PANEL: Array[StringName] = [&"ship", &"chart", &"archive"]

func music_state(state: StringName) -> void:
	if not _enabled or not STATES.has(state):
		return
	if state in PANEL and _cue != &"":
		return
	var entry: Array = STATES[state]
	var cue: StringName = entry[0]
	var level: int = entry[1]
	if state == &"sector":
		cue = _sector_cue()
		if cue == &"dread":
			level = mini(level, DEEP_MAX)
	elif DEEP.has(cue) and state in DEEP_STATES and _danger() >= DREAD_DANGER:
		cue = DEEP[cue]
		level = mini(level, DEEP_MAX)
	play_cue(cue, level)

## WHAT A SECTOR SOUNDS LIKE IS A FACT ABOUT THE SECTOR.
##
## Every cue used to be chosen by which SCREEN you were looking at, which is why
## opening a panel changed the music and why six of the thirteen written cues
## were unreachable: STATES only named seven places and there are thirteen
## pieces. The map already knows far more than seven things about where you are.
##
## In order, because the first that applies wins:
##
##   DANGER. Past DREAD_DANGER the soundtrack admits it, which is the ruling the
##   DEEP table already carried and the only one that outranks geography.
##
##   FAUNA. A migration route is the one thing in this game that is alive and
##   indifferent to you, and `fauna` is a property of the node rather than of an
##   encounter -- so the music belongs to the place, like everything else here.
##
##   DEPTH. Otherwise the galaxy itself: four bands across fifteen layers, from
##   the edge you left to the core you are heading into. The innermost band
##   starts at DEEP_FROM, so it lines up with the boundary the map generator
##   already uses rather than inventing a second one.
##
##     0      First Light    the widest arch in the set, written as an opener,
##                            and now literally the first thing a run plays
##     1-3    Home           the only arch that comes home to the note it left
##     4-6    Shells         a map of somewhere you have not been
##     7-10   The Long Way Home
##     11-14  Core           the further in you go, the lower it gets
func _sector_cue() -> StringName:
	if Run.map.is_empty():
		return &"theme"
	var n: MapGen.MapNode = Run.node_at()
	if n == null:
		return &"theme"
	if n.danger >= DREAD_DANGER:
		return &"dread"
	if n.fauna:
		return &"fauna"
	for band: Array in SECTOR_BANDS:
		if n.layer >= int(band[0]):
			return band[1]
	return &"first_light"

## The depth bands, as data rather than as an if-chain, so `audiotest` can read
## them. Deepest first; the first whose floor the layer reaches wins.
const SECTOR_BANDS: Array = [
	[MapGen.DEEP_FROM, &"core"], [7, &"theme"], [4, &"shells"], [1, &"home"],
	[0, &"first_light"],
]
## The two sector cues that are not about depth at all.
const SECTOR_SPECIAL: Array[StringName] = [&"dread", &"fauna"]

func _danger() -> int:
	# Screens can change before a run exists (menu, first boot), and node_at()
	# indexes straight into the map, so the empty case has to be caught here.
	if Run.map.is_empty():
		return 0
	var n: MapGen.MapNode = Run.node_at()
	return 0 if n == null else n.danger

## Start a cue, or move an already-running one to a new intensity. Changing
## intensity never restarts anything.
func play_cue(cue: StringName, level: int) -> void:
	if not _enabled or not (CUES.has(cue) or TRACKS.has(cue)):
		return
	# Clamped against the cue's OWN rungs. A finished track has one, so every
	# rung a caller asks for lands on it — STATES still names a level for the
	# title and does not need to know the piece is not layered.
	_intensity = clampi(level, 0, _layers(cue).size() - 1)
	if _cue == cue:
		_pending = &""
		_apply_layers()
		return

	# TWO CUES MAY ONLY SOUND TOGETHER IF THEY SHARE A ROOT.
	#
	# Where they do -- the DEEP group, all on F -- the overlap is the whole
	# point: the swap is meant to read as the PLACE TURNING rather than as the
	# music changing, and it only does that because the harmony holds under it.
	#
	# Where they do not, they are simply two pieces in two keys at two tempos,
	# and playing them at once for two seconds is a collision, not a transition.
	# So an unrelated cue waits for silence: everything fades out, and the new
	# one starts when nothing else is sounding. It costs about 1.6 seconds and
	# reads as the music changing because the place did, which is true.
	var related: bool = _cue == &"" or ROOT.get(cue, &"?") == ROOT.get(_cue, &"!")
	_cue = cue
	_ensure_loaded(cue)
	if related:
		_pending = &""
		_rate = CROSSFADE
		_start(cue, false)
		for c: StringName in _stems:
			_gain_target[c] = 1.0 if c == cue else 0.0
	else:
		_pending = cue
		_rate = SWITCH
		for c: StringName in _stems:
			_gain_target[c] = 0.0
	_apply_layers()

func stop_music() -> void:
	for c: StringName in _stems:
		_gain_target[c] = 0.0
	_cue = &""
	_pending = &""

## Per-stem target volume: audible if the cue is running and the stem's rung
## has been reached, silent otherwise. Actual movement happens in _process.
## The rungs a cue actually has. A finished track has exactly one.
func _layers(cue: StringName) -> Array:
	return [[WHOLE]] if TRACKS.has(cue) else CUES[cue]

func _apply_layers() -> void:
	for cue: StringName in _stems:
		var layers: Array = _layers(cue)
		for level in layers.size():
			for stem: StringName in layers[level]:
				var p: AudioStreamPlayer = _stems[cue][stem]
				p.set_meta(&"on", cue == _cue and level <= _intensity)

func _ensure_loaded(cue: StringName) -> void:
	if _stems.has(cue):
		return
	var players: Dictionary = {}
	var layers := _layers(cue)
	for level in layers.size():
		for stem: StringName in layers[level]:
			var path: String = TRACKS[cue] if TRACKS.has(cue) 				else MUSIC_DIR % [cue, stem]
			var stream: AudioStream = load(path)
			if stream == null:
				push_warning("Audio: missing music stem %s/%s" % [cue, stem])
				continue
			# The files are rendered as seamless loops; tell the stream to use
			# that rather than stopping at the end of the phrase.
			if stream is AudioStreamOggVorbis:
				(stream as AudioStreamOggVorbis).loop = true
			elif stream is AudioStreamMP3:
				# Same reason, different container. Without it the title screen
				# plays once and then sits in silence.
				(stream as AudioStreamMP3).loop = true
			var p := AudioStreamPlayer.new()
			p.stream = stream
			p.bus = &"Music"
			p.volume_db = OFF_DB
			p.set_meta(&"on", false)
			add_child(p)
			players[stem] = p
	_stems[cue] = players
	_gain[cue] = 0.0
	_gain_target[cue] = 0.0
	_running[cue] = false
	# A CUE IS IDLE FROM THE MOMENT IT IS LOADED, NOT FROM THE MOMENT IT STOPS.
	#
	# `_idle_since` was only ever written by `_stop`, which meant a cue that was
	# loaded and then never started had no entry at all -- and `_release_idle`
	# reads a missing entry as `now`, so the age is always zero and it can never be
	# let go. Nothing could reach that state until unrelated cue changes began
	# deferring: ask for three different cues inside three frames and the first
	# two are loaded, superseded before they ever sound, and resident for the
	# rest of the session. audiotest caught it on the first run, which is the
	# entire reason that test exists.
	_idle_since[cue] = Time.get_ticks_msec()

## Every stem of a cue starts in the same frame, so they share a mix cycle and
## stay sample-locked. They are all exactly the same length, so they also loop
## together and cannot drift apart over a long session.
## When the soundtrack started, in msec. Everything plays against this clock.
var _music_t0: int = 0


## A CUE RESUMES WHERE IT WOULD HAVE BEEN, rather than starting again.
##
## This used to be a bare `play()`, which begins at the top of the loop. Ship,
## starchart and sector are three different cues, so walking between them
## restarted the music every single time -- the most common thing a player does
## in this game was also the one thing guaranteed to interrupt it.
##
## Every stem is a seamless loop, so there is nothing special about the start of
## one. Playing from `elapsed % length` puts a cue where it would be if it had
## never stopped, and because ALL cues are measured against ONE clock they stay
## in phase with each other as well -- switching screens now reads as the same
## piece changing colour rather than as a new track beginning.
##
## All six stems of a cue share a length, so they stay locked to each other.
## A CUE THAT IS ARRIVING ON ITS OWN STARTS AT ITS BEGINNING.
##
## The paragraph above was written for the second edition and its first line is
## now false. "There is nothing special about the start of one" was true of a
## texture: a pedal with events over it sounds the same wherever you join it.
## Every cue is a written piece now, with an opening statement, an answer, a
## section that goes somewhere else and a return -- so joining at a clock
## position means you almost never hear the idea stated, and you frequently
## arrive in the middle of the B section, which is the one part written to sound
## like being a long way from home.
##
## So the phase resume is kept for exactly the case it was invented for: a DEEP
## swap between two cues that share a root, where holding position is what makes
## the pair read as one place turning rather than two pieces. Everything else
## starts at bar one.
func _start(cue: StringName, from_top: bool = true) -> void:
	if _running.get(cue, false):
		return
	_running[cue] = true
	if _music_t0 == 0:
		_music_t0 = Time.get_ticks_msec()
	var elapsed := float(Time.get_ticks_msec() - _music_t0) / 1000.0
	for stem: StringName in _stems[cue]:
		var p: AudioStreamPlayer = _stems[cue][stem]
		var at := 0.0
		if not from_top and p.stream != null:
			var len := p.stream.get_length()
			if len > 0.0:
				at = fposmod(elapsed, len)
		p.play(at)

## A cue that has finished fading out is left holding eight or nine Ogg streams
## decoding into silence. Stop it. Coming back restarts it from bar 1, which is
## what a crossfade between two different pieces wants anyway.
func _stop(cue: StringName) -> void:
	if not _running.get(cue, false):
		return
	_running[cue] = false
	_idle_since[cue] = Time.get_ticks_msec()
	for stem: StringName in _stems[cue]:
		(_stems[cue][stem] as AudioStreamPlayer).stop()


## How long a silent cue is kept loaded before its streams are let go.
##
## STOPPING A CUE WAS NEVER RELEASING IT. `_ensure_loaded` loads on first use
## and nothing ever undid it, so a session that visited the title, the chart,
## the ship, a station, a sector, an event, a fight and a boss ended up holding
## every one of those cues decoded in memory at once -- the whole set is 154 MB
## of Ogg and the per-cue figures run to 17 MB. The README calls download size
## "the one number in the project that is getting uncomfortable"; this is the
## half of that number a player actually pays, mid-run, on the machine they are
## playing on.
##
## THE DELAY IS THE WHOLE DESIGN. Releasing the moment a cue goes silent would
## make walking chart -> ship -> chart reload a cue twice in ten seconds, and
## loading eight stems is a hitch you would feel. Forty-five seconds is longer
## than any round trip through the menus and far shorter than a run.
const RELEASE_AFTER_MS := 45000
var _idle_since: Dictionary = {}    ## cue -> msec when it last went silent


## Let go of anything that has been silent long enough. Never the current cue,
## whatever its gain is doing: a cue mid-crossfade is still the answer to "what
## is playing", and freeing it would cut the fade it is in the middle of.
func _release_idle() -> void:
	var now := Time.get_ticks_msec()
	for cue: StringName in _stems.keys():
		if cue == _cue or _running.get(cue, false):
			continue
		if now - int(_idle_since.get(cue, now)) < RELEASE_AFTER_MS:
			continue
		for stem: StringName in _stems[cue]:
			var p: AudioStreamPlayer = _stems[cue][stem]
			# The stream is what holds the memory; drop it before the node so
			# the resource's last reference goes with the player rather than
			# waiting on whatever else happens to be holding the node.
			p.stream = null
			p.queue_free()
		_stems.erase(cue)
		_gain.erase(cue)
		_gain_target.erase(cue)
		_running.erase(cue)
		_idle_since.erase(cue)


## How many cues are loaded right now. For `-- audiotest`; nothing in the game
## asks.
func resident() -> Array:
	var out := _stems.keys()
	out.sort()
	return out

func _process(delta: float) -> void:
	if not _enabled or _stems.is_empty():
		return
	_release_idle()
	if _stems.is_empty():
		return
	# A CUE WAITING FOR SILENCE GETS IT, AND THEN STARTS FROM THE TOP. Promoted
	# here rather than in play_cue because only this loop knows when the last
	# gain actually reached zero -- and starting the new piece a frame early is
	# the whole fault this exists to avoid.
	if _pending != &"":
		var quiet := true
		for cue: StringName in _stems:
			if cue != _pending and _gain[cue] > 0.001:
				quiet = false
		if quiet:
			var up := _pending
			_pending = &""
			_start(up, true)
			_gain_target[up] = 1.0

	for cue: StringName in _stems:
		var g: float = _gain[cue]
		var t: float = _gain_target[cue]
		if not is_equal_approx(g, t):
			g = move_toward(g, t, delta / maxf(_rate, 0.05))
			_gain[cue] = g
		# SILENT AND STAYING SILENT MEANS STOP, WHETHER OR NOT IT WAS MOVING.
		# This used to live inside the branch above, so a cue was only ever
		# stopped on the frame its fade actually arrived at zero. A cue that was
		# left ALREADY at zero never got that frame: gain and target both 0 are
		# equal, the branch is skipped, `_stop` is never reached, and `_running`
		# stays true for the rest of the session. Its players keep decoding Ogg
		# into silence and `_release_idle` skips it *because* it is running --
		# so the leak this whole file guards against was reachable by the most
		# ordinary action there is.
		#
		# It happens whenever a cue is crossfaded away from before its fade-in
		# has moved: boot to the title and leave within about two seconds, which
		# a player does every single run. It hid because `audiotest` played a
		# list that always happened to contain whatever cue the menu used, so
		# the stuck cue was re-taken as current before anything looked at it.
		if g <= 0.0 and t <= 0.0:
			_stop(cue)
		if not _running.get(cue, false):
			continue
		for stem: StringName in _stems[cue]:
			var p: AudioStreamPlayer = _stems[cue][stem]
			var want: float = 0.0 if not p.get_meta(&"on", false) else 1.0
			var lv: float = move_toward(_stem_level(p), want, delta / FADE)
			p.set_meta(&"lv", lv)
			var v: float = lv * g
			p.volume_db = OFF_DB if v <= 0.001 else linear_to_db(v)

func _stem_level(p: AudioStreamPlayer) -> float:
	return float(p.get_meta(&"lv", 0.0))

# ---------------- sound effects ----------------

## ONE VOICE PER HOLD/HULL ACTION, wherever a screen triggers it. Three screens
## hand-picked these name-and-pitch pairs independently and `module_install`
## had already drifted to two different variances between them -- each site read
## as locally correct, so nothing caught it. The pair is data; it lives once.
const ACT_SFX: Dictionary = {
	&"module_install": 0.04,
	&"module_uninstall": 0.05,
	&"module_scrap": 0.05,
	&"hull_transfer": 0.03,
}

func act(name: StringName) -> void:
	play(name, float(ACT_SFX.get(name, 0.06)))


## pitch_var randomises playback rate a little, which is what keeps a click
## you hear four hundred times an hour from turning into a machine gun.
## limit_ms drops repeats inside a window, for signals that fire in bursts.
## `db` is an OFFSET, and it is new. Every cue played at whatever level it was
## mastered at, which is right for a game where each sound happens once at a
## moment that earned it -- and wrong the moment one of them starts happening
## six times a system. `loot_drop` is written as a reward sting; taking a crate
## off the floor does not deserve one, but the alternative was authoring a second
## quieter file rather than turning the existing one down.
func play(name: StringName, pitch_var: float = 0.06, limit_ms: int = 0,
		db: float = 0.0) -> void:
	if not _enabled:
		return
	var now := Time.get_ticks_msec()
	# SUPPRESSION IS NOT A RATE LIMIT, and it was only ever read as one. `suppress`
	# writes a moment in the future into `_last`, and that was checked solely when
	# the caller passed a limit -- so `Sig.jumped`, which plays `jump` with none,
	# went straight through, and the convoy crack played on every jump it had been
	# silenced for. The sound tape in `jumpcine whole` is what caught it.
	if int(_last.get(name, 0)) > now:
		return
	if limit_ms > 0 and now - int(_last.get(name, -limit_ms)) < limit_ms:
		return
	_last[name] = now
	# Round robins: a name with `name_2.wav`, `name_3.wav`... beside it
	# plays a random take.  One file per shot always reads as a toy, no
	# matter how good the file is -- the ear catches the exact repeat.
	var pick := name
	var vars: Array = _variants.get(name, [])
	if vars.is_empty() and not _variants.has(name):
		vars = [name]
		for i in range(2, 5):
			var vn := StringName("%s_%d" % [name, i])
			if ResourceLoader.exists(SFX_PATH % vn):
				vars.append(vn)
		_variants[name] = vars
	if vars.size() > 1:
		pick = vars[randi() % vars.size()]
	var stream: AudioStream = _cache.get(pick)
	if stream == null:
		stream = load(SFX_PATH % pick)
		if stream == null:
			push_warning("Audio: missing sfx %s" % pick)
			return
		_cache[pick] = stream
	# Round-robin the pool. Fourteen voices is more than the game ever asks
	# for at once; stealing the oldest is the right failure if it ever does.
	var p := _sfx[_sfx_next]
	# WHATEVER THIS VOICE WAS DOING, IT IS NOT DOING IT NOW. A hush left a tween
	# pulling this player's volume toward silence; reusing it without killing
	# that would start the new sound and fade it out underneath itself.
	if _fade[_sfx_next] != null and _fade[_sfx_next].is_valid():
		_fade[_sfx_next].kill()
	_fade[_sfx_next] = null
	_sfx_next = (_sfx_next + 1) % _sfx.size()
	p.stream = stream
	p.pitch_scale = 1.0 + randf_range(-pitch_var, pitch_var)
	p.volume_db = db
	# WHAT THIS VOICE IS CARRYING, so `hush` can find it again. The pick, not the
	# name asked for -- a round robin plays `thruster_arrive_c` when the caller
	# said `thruster_arrive`, and a hush naming either has to land.
	p.set_meta(&"cue", pick)
	p.set_meta(&"asked", name)
	if taping:
		tape.append([pick, Time.get_ticks_msec(), db, p.pitch_scale])
	p.play()

## Hold a name's tongue for a moment. The resource watcher plays loot_drop
## and scrap_gain on ANY cargo/credit increase -- right for a windfall,
## wrong layered over a screen that just played its own, better-informed
## sound for the same change. The screen calls this before it speaks.
func suppress(name: StringName, ms: int = 400) -> void:
	_last[name] = Time.get_ticks_msec() + ms


## Cut sounds that are still in the air, because what they were describing is
## over.
##
## THE OTHER HALF OF `suppress`, which only ever worked on a sound that had not
## started. Skipping the jump killed the tween that had the rest of the sequence
## in it and left everything ALREADY PLAYING to run on -- a 5.7-second warp over
## a sector that had finished arriving.
##
## FADED, NOT STOPPED. A stream cut between samples clicks, and on a hyperdrive
## at full level the click is louder than the sound it interrupted. 120 ms is
## under a frame and a half of the sequence being skipped and still long enough
## to land on zero.
##
## A name matches whether it was the one asked for or the take the round robin
## chose, so a caller hushes `thruster_arrive` without knowing which of the eight
## it got.
func hush(names: Array[StringName], fade_ms: int = 120) -> void:
	if not _enabled:
		return
	for i in _sfx.size():
		var p := _sfx[i]
		if not p.playing:
			continue
		if not (names.has(p.get_meta(&"cue", &"")) \
				or names.has(p.get_meta(&"asked", &""))):
			continue
		if _fade[i] != null and _fade[i].is_valid():
			continue                      ## already on its way out
		var t := create_tween()
		t.tween_property(p, "volume_db", p.volume_db - 40.0, fade_ms / 1000.0)
		t.tween_callback(p.stop)
		_fade[i] = t

func click() -> void:   play(&"ui_click", 0.05)
func hover() -> void:   play(&"ui_hover", 0.09, 40)
func back() -> void:    play(&"ui_back", 0.03)
func confirm() -> void: play(&"ui_confirm", 0.02)
func denied() -> void:  play(&"ui_denied", 0.03)

# ---------------- signal handlers ----------------

## The thermal ruling, made audible: ballistics run cold, energy weapons run
## hot. A card that prints heat gets the bright ionised zap; a card that does
## not gets the dry mechanical crack. You hear what a build is made of.
func _on_card_played(c: CardData) -> void:
	play(&"card_play", 0.05)
	if c.damage > 0 or c.damage_equals_heat or c.heat_scale > 0:
		# What the card mechanically IS picks the family; the files carry
		# round robins so no two shots are the exact same take.
		if c.charge_turns > 0:
			play(&"shot_heavy", 0.05)          # banked ordnance landing
		elif c.hits >= 2:
			play(&"shot_auto", 0.06)           # autocannon burst
		elif c.heat > 0 or c.damage_equals_heat or c.heat_scale > 0:
			play(&"shot_energy", 0.06)         # hot discharge
		else:
			play(&"shot_kinetic", 0.06)        # one cold slug
	elif c.vent > 0 or c.vent_all:
		play(&"vent", 0.05)
	elif c.block > 0 or c.brace > 0 or c.brace_from_heat:
		play(&"shield_block", 0.06)

## Heat is a second health bar you can choose to spend, and going over costs
## hull, which costs scrap. The warning is edge-triggered on the way up only:
## a tone every time heat moves while already hot would be unbearable across a
## long fight, and would stop meaning anything by turn three.
func _on_combat_state() -> void:
	var cap := Run.heat_cap()
	var hot: bool = cap > 0 and float(Run.heat) >= float(cap) * HEAT_WARN_AT
	if hot and not _hot:
		play(&"heat_warn", 0.02)
	_hot = hot

## Scrap and modules arrive from a dozen places — combat rewards, salvage,
## events, station stock, card effects — and not all of them emit the same
## signal. Chasing every site would mean a sound call in six files that each
## have to remember to keep it; watching the two totals instead means the
## sound is right by construction. One of these two signals always fires
## after anything has changed.
func _poll_resources() -> void:
	var credits := Run.credits
	var cargo := Run.cargo.size()
	if _last_credits >= 0 and credits > _last_credits:
		play(&"scrap_gain", 0.08, 110)
	if _last_cargo >= 0 and cargo > _last_cargo:
		play(&"loot_drop", 0.03, 200)
	_last_credits = credits
	_last_cargo = cargo

## A kill flashes warm and dies cold -- but WHAT died decides the sound.
## Bosses get the two-stage reactor death with the tritone in the debris;
## fauna do not explode at all, because one of the warm things going out is
## a loss even when it was trying to eat you. limit_ms: a card that clears
## a board is one explosion, not a drum roll.
func _on_enemy_destroyed(who: int) -> void:
	var t: EnemyTemplate = null
	if Router.combat != null and who >= 0 and who < Router.combat.enemies.size():
		t = Router.combat.enemies[who].template
	if t != null and t.fauna:
		play(&"fauna_falls", 0.04, 400)
	elif t != null and (t.boss or t.miniboss):
		play(&"explosion_boss", 0.03, 400)
	else:
		play(&"explosion_small", 0.09, 160)

func _on_damage(_amount: int, to_player: bool, _who: int) -> void:
	if to_player:
		play(&"impact_hull", 0.05)
	else:
		# Your shot landing on THEM: distance runs cold, so it is small and
		# dry. limit_ms keeps multi-hit turns from machine-gunning it.
		play(&"impact_enemy", 0.08, 90)

func _on_combat_ended(result: StringName, _summary: String) -> void:
	match result:
		&"victory", &"won", &"pacified": play(&"victory", 0.0)
		&"fled": play(&"ui_tab", 0.03)
		_: pass          ## death is handled by run_ended, so it is not doubled

func _on_run_ended(won: bool, _reason: String) -> void:
	if won:
		play(&"victory", 0.0)
	# AND NOTHING WHEN YOU DIE. There was a two-second sting here, F to Gb on a
	# low bowed note, and the reasoning was sound: the semitone is the whole idea
	# of the dread cue, so dying sounded like the thing that had been following
	# you all run. What it actually did was announce the ending over the top of a
	# cue written to BE the ending -- "No Fault" is a line that falls three times
	# and does not come back up, and it does not need help. Silence, and then the
	# music that is already the answer.

# ---------------- volume ----------------

func set_volume(bus: StringName, value: float) -> void:
	value = clampf(value, 0.0, 1.0)
	match bus:
		&"Master": master_volume = value
		&"Music": music_volume = value
		&"SFX": sfx_volume = value
	_apply_volumes()
	save_settings()

func volume_of(bus: StringName) -> float:
	match bus:
		&"Music": return music_volume
		&"SFX": return sfx_volume
		_: return master_volume

func _apply_volumes() -> void:
	for pair in [[&"Master", master_volume], [&"Music", music_volume], [&"SFX", sfx_volume]]:
		var idx := AudioServer.get_bus_index(pair[0])
		if idx < 0:
			continue
		var v: float = pair[1]
		# Faders are linear because that is what a slider position means to a
		# player; the bus wants dB. Zero is a mute, not -inf dB.
		AudioServer.set_bus_mute(idx, v <= 0.001)
		AudioServer.set_bus_volume_db(idx, linear_to_db(maxf(v, 0.001)))

## Shares user://settings.cfg with DisplaySettings, in its own section.
func save_settings() -> void:
	var cfg := ConfigFile.new()
	cfg.load(DisplaySettings.PATH)            ## keep the display section
	cfg.set_value("audio", "master", master_volume)
	cfg.set_value("audio", "music", music_volume)
	cfg.set_value("audio", "sfx", sfx_volume)
	cfg.save(DisplaySettings.PATH)

func load_settings() -> void:
	var cfg := ConfigFile.new()
	if cfg.load(DisplaySettings.PATH) == OK:
		master_volume = float(cfg.get_value("audio", "master", master_volume))
		music_volume = float(cfg.get_value("audio", "music", music_volume))
		sfx_volume = float(cfg.get_value("audio", "sfx", sfx_volume))
	_apply_volumes()
