"""The drive, and the five ways it gives out on arrival.

    py -3.14 flameout.py

THE SOUND IS A RECORDING NOW. It was a synthesised rotor -- a 25.5 Hz buzz
through a measured spectral envelope, bitcrushed with the same recipe as the
Four Bit lead -- and it was fine, but Jon has a better source for it. What plays
is an ElevenLabs generation from:

    "sci fi, powerful space ship thruster roaring at regular speed. No
     background noises, just the roaring flames and engine"

That prompt is why it fits: no background, no room, no tail. A clean four-second
roar with nothing else in it is exactly what you want when the thing you need to
do to it is cut it into pieces.

PROVENANCE, AND THE ONE THING TO CHECK BEFORE SHIP. The file came from
ElevenLabs but was generated by somebody else, not on Jon's account. Commercial
rights are clear on audio your own account generates and murkier on audio taken
from a library entry, so if this ships, regenerating it from the prompt above on
his own account costs a few credits and removes the question entirely. Nothing
else would change: it would be dropped in at the same path and re-rendered.

    audio/samples/thruster_roar.mp3

`audio/samples/` is gitignored -- the same rule the CC0 instrument libraries
follow, and for the same reason: source audio is a build input, the rendered
result is what ships. So a fresh checkout has the five clips in assets/ and can
play them; only RE-rendering needs the source put back.

------------------------------------------------------------------------------
WHY THE FIVE PATTERNS EXIST, which is the older half of this file.

The engines guttering out on arrival was one fixed pattern: burn clean to 42% of
the approach, blink six times on a falling duty cycle, coast the rest dark. Good
the first time and a metronome by the tenth, because it was the same six blinks
at the same six moments every system.

THE CATCH IS THAT THE SOUND IS GATED BY THE PICTURE. The clip is the roar with
`ShipView._flame_lit` cut into it, so the flashes you hear are the flashes you
see. Randomising either end alone slides them apart, and a flame lighting 40 ms
after its own sound reads as broken rather than as varied -- worse than the
metronome it was meant to fix.

So neither end improvises. This file generates five patterns, writes them into
ShipView.gd as a table, and cuts one clip per row from that same table. The
flame reads row i; the clip for row i was made from row i. They cannot drift,
because there is nothing for them to drift from.

WHY A TABLE AND NOT A SHARED FORMULA. The same generator written twice, once in
GDScript and once here, is two generators that agree until somebody edits one --
and they would disagree silently, in the one way that matters. A table written
once is one generator with two readers.

A ROW IS THE FLAME'S LIT WINDOWS, in arrival progress from 0 to 1, and the first
window is the clean burn. That makes the rule at both ends "lit if e falls
inside a span", with no special case for the head and none for the tail.

WHAT STAYS FIXED. Every pattern burns clean for roughly the first two seconds,
coughs with shrinking flashes at growing intervals, and leaves a second and a
half of dark unpowered drift at the end, which is the part of the approach worth
having. What varies is when the burn gives out, how many coughs it takes to die,
and where they fall.
"""
from __future__ import annotations

import io
import os
import subprocess
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import synth                                                    # noqa: E402
from synth import SR, lp                                        # noqa: E402

SHIPVIEW = os.path.join(HERE, "..", "scripts", "ui", "ShipView.gd")
SFX = os.path.join(HERE, "..", "assets", "audio", "sfx")
ROAR = os.path.join(HERE, "samples", "thruster_roar.mp3")

HEAD = "## GENERATED BY audio/flameout.py -- do not hand-edit; run it instead."
TAIL = "## -- end of the generated table."

## STRAIGHT OUT OF ShipView.gd. The clock the whole pattern is measured in, and
## the one number the two ends still have to agree on by hand.
ARRIVE_S = 4.5

## Five ways to die. Enough that two arrivals running are unlikely to match,
## few enough that the set still reads as one drive behaving one way rather
## than as five different engines.
NAMES = ("a", "b", "c", "d", "e")

## Where the clean burn can give out, and where the last cough can land. Both
## brackets sit around the numbers the fixed version used (0.42 and 0.66), so
## the average arrival is the one that was already approved.
FADE = (0.385, 0.470)
OUT = (0.580, 0.715)
## The first cough and the first gap after it, in progress. 0.036 of a 4.5 s
## approach is 162 ms -- long enough to read as the engine still trying.
ON_0 = (0.030, 0.042)
GAP_0 = (0.008, 0.016)
## And how they run down. Flashes shrink, gaps grow; that asymmetry is what
## starving sounds like, and reversing either one sounds like starting up.
ON_DECAY = (0.68, 0.86)
GAP_GROW = (1.05, 1.35)
## A flash shorter than this is under two frames on screen: a flicker rather
## than the engine catching. Below it the drive is simply out.
MIN_ON = 0.006
## And never fewer than this many coughs. One is a switch being thrown, which
## is the thing the whole stutter exists to avoid.
MIN_COUGHS = 4

## THREE ENGINES OUT OF ONE RECORDING, one per hull weight class.
##
## The game's own word is weight, not size, and the ladder is LIGHT / MEDIUM /
## HEAVY -- so these are named for the enum in HullData rather than for the
## thing they sound like. `medium` is the roar as generated; the other two are
## it moved, and moved in the two ways that actually read as mass:
##
##   rate    read faster or slower, which takes the pitch with it. A big engine
##           turns over slower. This is the whole of it, and the rest is trim.
##   tilt    a shelf either side of 180 Hz. Heavy keeps its bottom and loses
##           its edge; light does the reverse. Without it a resampled clip just
##           sounds like the same engine on a tape at the wrong speed.
##
## THE PITCH SHIFT IS SAFE HERE AND WOULD NOT BE AT RUNTIME. Godot's
## `pitch_scale` resamples on playback, so it is a TIME shift as well -- it
## would slide the coughs off the flame, which is the one thing this whole file
## exists to prevent. Done here it is free: the source is resampled first and
## the gate is cut afterwards, at the true time base, so every flash still
## lands on its own frame.
## The tilt is the LOW shelf's gain, so heavy is the positive one. Written out
## the wrong way round first, and the measurement caught it in one line: heavy
## came back with the HIGHEST centroid of the three and the least energy under
## 200 Hz, which is the opposite of a big engine in every respect.
## LEVEL IS PART OF IT AFTER ALL, and this is the second thing the ladder has
## taught me. It was here, then it came out on the argument that the size has to
## be in the sound rather than in the fader -- which is true about a drive that
## is ONLY louder, and wrong as a reason to make them all the same. A bigger
## engine moves more air. Jon heard the flat set and said so straight away: the
## light one should be quieter and lighter, the heavy one deeper and louder.
##
## What actually broke it the first time was never the ladder, it was the
## CEILING: heavy asked to be louder, ran into the peak limit, got pulled back,
## and landed quieter than medium. So the ladder hangs off the ceiling now --
## heavy sits just under it and the other two step down from there -- and the
## limiter is left with nothing to do, which is the only state a limiter should
## ever be in on a rendered asset.
##
##   rate    read faster or slower, which takes the pitch with it. A big engine
##           turns over slower, and this is still most of the difference.
##   tilt    a shelf either side of 180 Hz. Heavy keeps its bottom and loses its
##           edge; light does the reverse, which is what "lighter" means.
##   drive   soft clipping, on heavy only. See `cut`: it is what lets a deep
##           sound be a loud one. Without it heavy could not be raised at all --
##           it hit the peak ceiling 8 dB before it got level with the others.
##   a_db    A-WEIGHTED, not RMS, and that is the whole correction. 2.6 dB a
##           step, heavy loudest, anchored where medium runs out of headroom.
WEIGHTS = (
    ("light", 1.300, -3.0, -33.6, 0.0),
    ("medium", 1.000, 0.0, -31.0, 0.0),
    ("heavy", 0.850, +4.0, -28.4, 2.5),
)
## Where the tilt pivots. Below it is the engine's body, above it the flames.
TILT_HZ = 180.0
## Where the tilt pivots. Below it is the engine's body, above it the flames.

## LEAVING, which is the approach run backwards in every respect that matters.
##
## Straight out of ShipView: the lean lasts DEPART_MS and the flare peaks 0.17 s
## after it, so the clip covers both and hands the bang over to `jump` -- the
## flare's own sfx, which Sig.jumped already fires on exactly that frame. One
## pulse, already wired, already in the game's vocabulary.
DEPART_S = 0.90
DEPART_TAIL_S = 0.25
## The drive spooling: it starts well below its running speed and comes up past
## it. The approach's rotor SLOWS as it starves; this is that gesture inverted,
## and inverting it is the whole reason it reads as power rather than as a fade.
SPOOL_FROM = 0.62
SPOOL_TO = 1.12
## And it comes up from almost nothing. Jon asked for the arrival's engines to
## swell as the ship gets into frame; a departure is the same idea with the ship
## already there, so the swell is all of it.
SPOOL_QUIET_DB = -22.0
## And the whole spool sits a shade under the arrivals. Not a judgement about
## how loud leaving should be -- it is headroom. A rev is one continuous swell
## with no gate cut into it, so its crest factor is lower than a flameout's and
## at the arrivals' own level two of the three ran 0.7 and 1.4 dB into the
## ceiling. The ladder between the weights is untouched; all three move together.
DEPART_A_TRIM = -1.6

## Where to start reading the roar. It opens a little under its own steady
## level -- measured at -7 dBFS over the first half second against -5 after --
## and an arrival is a ship already at speed, not one lighting up.
ONSET_SKIP = 0.30
## Folded back over the head to make the roar loop without a seam.
WRAP_S = 0.35
## How much of an edge to put on each gated flash. The picture switches frames
## for free; audio cannot, and seven hard switches is seven clicks.
EDGE_S = 0.003
## THE ENGINE WINDS DOWN, NOT OFF. Across the stutter the playback rate falls to
## this and a lowpass closes over it, which is the difference between a drive
## losing power and a drive being turned down. A mixer fade is the second one.
## The synthesised version slowed its rotor 33%; a recording gets the same
## gesture by being read slower, which drops its pitch with it.
RATE_FLOOR = 0.74
CLOSE_HZ = 800.0
## And silence a breath after the last flash. The approach runs the full 4.5 s
## but the last two of them are an unpowered coast, and rendering that as
## digital silence into a shipped file is a quarter megabyte of zeros per
## pattern. The ship keeps drifting without the file's help.
TAIL_S = 0.35

## THE CEILING, and it is no longer what the ladder hangs from -- MEDIUM is.
## Once heavy is saturated it has 8 dB of headroom and light has 7, while plain
## medium has 3.4, so medium is the one that runs out first and the ladder is
## anchored there. Worth writing down because it is not where you would look.
##
## It is a CHECK, not a stage. A limiter that fires on a rendered asset has
## quietly moved one clip relative to the others, which is how the first version
## of this ladder came out backwards; so it prints when it fires, and the fix is
## always to lower the level rather than to let it do the lowering.
LEVEL_PEAK_DB = -2.9


def a_weighted(x):
    """RMS through the A-weighting curve: what the level SOUNDS like.

    Plain RMS weights 30 Hz the same as 3 kHz and the ear does not come close.
    It cost a whole ladder to learn: heavy measured 5.3 dB louder than light by
    RMS and 7.1 dB QUIETER A-weighted, because it is nearly all below 200 Hz,
    and Jon heard the second number. Through a 200 Hz highpass -- a laptop
    speaker, near enough -- it was 9.1 dB quieter still.

    IEC 61672's analytic curve, applied in the frequency domain. Approximate as
    a loudness model and vastly closer than no model at all, which is what RMS
    is on material that differs this much in spectrum.
    """
    m = x.mean(axis=0) if x.ndim > 1 else x
    n = len(m)
    f = np.maximum(np.fft.rfftfreq(n, 1.0 / SR), 1e-6)
    f2 = f ** 2
    ra = (12194.0 ** 2 * f2 ** 2) / (
        (f2 + 20.6 ** 2) * np.sqrt((f2 + 107.7 ** 2) * (f2 + 737.9 ** 2))
        * (f2 + 12194.0 ** 2))
    y = np.fft.irfft(np.fft.rfft(m) * ra * 10 ** 0.1, n)
    return float(np.sqrt((y ** 2).mean()))


def _u(rs, lo_hi):
    lo, hi = lo_hi
    return lo + (hi - lo) * float(rs.rand())


def one(rs):
    """One way for the engine to starve, or None if it died too easily."""
    fade = _u(rs, FADE)
    ceiling = _u(rs, OUT)
    spans = [(0.0, fade)]
    at = fade
    on = _u(rs, ON_0)
    gap = _u(rs, GAP_0)
    while at + on <= ceiling and on >= MIN_ON:
        spans.append((at, at + on))
        at += on + gap
        on *= _u(rs, ON_DECAY)
        gap *= _u(rs, GAP_GROW)
    if len(spans) - 1 < MIN_COUGHS:
        return None
    return [(round(a, 4), round(b, 4)) for a, b in spans]


def build():
    """Five patterns, each from its own seed, rejecting the feeble ones.

    Seeded rather than random so that re-running this does not quietly hand the
    game five different sounds -- the table in ShipView and the clips in sfx/
    are checked in together and have to keep matching across a rebuild.
    """
    rows = []
    seed = 900
    while len(rows) < len(NAMES):
        r = one(np.random.RandomState(seed))
        seed += 17
        if r is not None:
            rows.append(r)
    return rows


def roar():
    """The source roar, decoded to this project's rate, as (2, N)."""
    if not os.path.exists(ROAR):
        raise SystemExit(
            "missing %s\n"
            "audio/samples/ is gitignored -- see this file's docstring. Put the\n"
            "ElevenLabs roar back at that path, or regenerate it from the prompt\n"
            "recorded there, and run this again." % ROAR)
    import imageio_ffmpeg
    import soundfile as sf
    wav = os.path.join(HERE, "out", "_roar.wav")
    os.makedirs(os.path.dirname(wav), exist_ok=True)
    subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(), "-v", "error", "-y",
                    "-i", ROAR, "-ar", str(SR), "-ac", "2", wav], check=True)
    y, _ = sf.read(wav, always_2d=True)
    src = y.T[:, int(ONSET_SKIP * SR):]
    # AND MADE ENDLESS. Four seconds is not enough: the longest pattern needs
    # 3.4 s of it, and the light hull reads at 1.15x, which wants 3.9. So the
    # last WRAP_S folds over the head, equal power, the same trick the beds
    # used -- a steady roar has no bar line and nothing to line the joint up
    # with, so the joint is simply made continuous instead.
    w = int(WRAP_S * SR)
    body = src[:, :src.shape[1] - w].copy()
    a = np.linspace(0.0, np.pi / 2, w)
    body[:, :w] = body[:, :w] * np.sin(a) + src[:, -w:] * np.cos(a)
    return body


def cut(src, spans, rate0=1.0, tilt_db=0.0, a_db=-34.0, drive=0.0):
    """One flameout, cut out of the roar at one weight class.

    The gate is the row; everything else here is the difference between an
    engine starving and a fader being pulled, and between a big one doing it
    and a small one.
    """
    fade = float(spans[0][1])
    out = float(spans[-1][1])
    total = out * ARRIVE_S + TAIL_S
    n = int(total * SR)
    t = np.arange(n) / SR
    e = np.clip(t / ARRIVE_S, 0.0, 1.0)
    fall = np.clip((e - fade) / max(out - fade, 1e-6), 0.0, 1.0)

    # READ SLOWER AS IT DIES. The read position is the running sum of the rate,
    # so the pitch falls with the speed the way a real one would -- rather than
    # the clip playing on at pitch and merely getting quieter.
    rate = rate0 * (1.0 - (1.0 - RATE_FLOOR) * fall)
    # Round the loop rather than off the end: the source is seamless, so the
    # read position wraps and a pattern can be any length it likes.
    pos = np.cumsum(rate) % src.shape[1]
    idx = np.arange(src.shape[1])
    y = np.vstack([np.interp(pos, idx, src[c]) for c in (0, 1)])

    # THE TILT, which is what stops a resample sounding like a tape at the
    # wrong speed. One shelf, both halves moved in opposite directions, so the
    # balance changes and the overall level does not.
    if abs(tilt_db) > 0.01:
        g = 10.0 ** (tilt_db / 20.0)
        lo = np.vstack([lp(y[c], TILT_HZ, order=2) for c in (0, 1)])
        y = lo * g + (y - lo) / g

    # And the filter closes over the same window.
    y = y * (1.0 - fall) + np.vstack([lp(y[c], CLOSE_HZ, order=2)
                                      for c in (0, 1)]) * fall * 1.25

    # SATURATION, WHICH IS HOW A DEEP SOUND STAYS AUDIBLE. A 110 Hz drive is
    # below where the ear is sensitive and below what a laptop speaker even
    # reproduces, so depth bought past a point is depth nobody hears. Softly
    # clipping it folds energy up into 220 and 330 Hz -- the ear reconstructs
    # the fundamental from those, and a small speaker passes them. It also
    # lowers the crest factor, which buys real level under the same ceiling.
    #
    # Which is what a big engine is anyway: dense, not merely low.
    if drive > 0.0:
        k = 1.0 + drive
        y = np.tanh(y * k) / np.tanh(k)

    # `_flame_lit`, transcribed -- which is now just "is e inside a span".
    lit = np.zeros(n)
    for a, b in spans:
        lit[(e >= a) & (e < b)] = 1.0
    k = max(int(EDGE_S * SR), 1)
    w = np.hanning(2 * k + 1)
    gate = np.convolve(lit, w / w.sum(), mode="same")
    gate = gate * np.clip((total - t) / 0.9, 0.0, 1.0)
    y = y * gate

    y *= 10.0 ** (a_db / 20.0) / max(a_weighted(y), 1e-12)
    # A CHECK, NOT A STAGE. If this ever fires it has quietly moved one clip
    # relative to the other fourteen, so it says so rather than doing it in
    # silence -- which is exactly how the level ladder above went wrong.
    ceil = 10.0 ** (LEVEL_PEAK_DB / 20.0)
    m = float(np.abs(y).max())
    if m > ceil:
        print("    ceiling clipped %.1f dB off this one -- lower its a_db"
              % (20.0 * np.log10(m / ceil)))
        y *= ceil / m
    k = max(int(0.002 * SR), 1)
    a = (1.0 - np.cos(np.linspace(0.0, np.pi, k))) / 2.0
    y[:, :k] *= a
    y[:, -k:] *= a[::-1]
    return y


def check_weights():
    """The table's row order IS HullData.Weight. Prove it rather than trust it.

    FLAMEOUT_SFX is indexed with `int(hull.weight)`, so reordering WEIGHTS here
    would hand every light hull the heavy clips and say nothing at all about it.
    Two lines of parsing to turn that into a failed build.
    """
    src = io.open(os.path.join(HERE, "..", "scripts", "data", "HullData.gd"),
                  encoding="utf-8").read()
    line = next(l for l in src.splitlines() if l.startswith("enum Weight"))
    got = [w.strip().lower() for w in
           line.split("{", 1)[1].split("}", 1)[0].split(",") if w.strip()]
    mine = [w for w, _rate, _tilt, _a, _dr in WEIGHTS]
    if got != mine:
        raise SystemExit("WEIGHTS is %s but HullData.Weight is %s -- the table "
                         "is indexed by the enum, so they must agree"
                         % (mine, got))


def spool(src, rate0=1.0, tilt_db=0.0, a_db=-34.0, drive=0.0):
    """The drive coming up, at one weight class.

    The same source, the same ladder and the same levelling as the arrival, so
    the ship leaving sounds like the ship that arrived rather than like a second
    ship somebody bought in. Only the gesture is reversed.
    """
    total = DEPART_S + DEPART_TAIL_S
    n = int(total * SR)
    t = np.arange(n) / SR
    e = np.clip(t / DEPART_S, 0.0, 1.0)

    # Rate rises, so the pitch rises with it. Eased so most of the change
    # happens late: a drive spends a while turning over before it bites.
    rate = rate0 * (SPOOL_FROM + (SPOOL_TO - SPOOL_FROM) * e ** 2.2)
    pos = np.cumsum(rate) % src.shape[1]
    idx = np.arange(src.shape[1])
    y = np.vstack([np.interp(pos, idx, src[c]) for c in (0, 1)])

    if abs(tilt_db) > 0.01:
        g = 10.0 ** (tilt_db / 20.0)
        lo = np.vstack([lp(y[c], TILT_HZ, order=2) for c in (0, 1)])
        y = lo * g + (y - lo) / g

    # The filter OPENS across the spool, the mirror of the arrival closing it.
    y = y * e + np.vstack([lp(y[c], CLOSE_HZ, order=2)
                           for c in (0, 1)]) * (1.0 - e) * 1.25

    if drive > 0.0:
        k = 1.0 + drive
        y = np.tanh(y * k) / np.tanh(k)

    # The swell, and then it is simply gone -- the flare takes the ship on the
    # frame after this ends, so there is nothing to decay into.
    q = 10.0 ** (SPOOL_QUIET_DB / 20.0)
    y *= q + (1.0 - q) * e ** 1.6
    y *= np.clip((total - t) / DEPART_TAIL_S, 0.0, 1.0) ** 0.6

    y *= 10.0 ** (a_db / 20.0) / max(a_weighted(y), 1e-12)
    ceil = 10.0 ** (LEVEL_PEAK_DB / 20.0)
    m = float(np.abs(y).max())
    if m > ceil:
        print("    ceiling clipped %.1f dB off this one -- lower its a_db"
              % (20.0 * np.log10(m / ceil)))
        y *= ceil / m
    k = max(int(0.002 * SR), 1)
    a = (1.0 - np.cos(np.linspace(0.0, np.pi, k))) / 2.0
    y[:, :k] *= a
    y[:, -k:] *= a[::-1]
    return y


def write_gd(rows):
    """Put the table into ShipView.gd, between its own markers."""
    check_weights()
    out = [HEAD,
           "##",
           "## Each row is one way for the drive to starve: the lit windows of",
           "## the flame, in arrival progress. The first window is the clean",
           "## burn, so the rule is just 'lit if e falls inside a span'.",
           "##",
           "## THE SOUND IS CUT FROM THESE SAME ROWS -- sfx/thruster_arrive_a",
           "## is row 0 gated by row 0 -- so editing a number here without",
           "## re-running flameout.py slides the picture off the sound, which",
           "## is the one thing this must never do.",
           "const FLAMEOUTS := ["]
    for r in rows:
        out.append("\t[%s],"
                   % ", ".join("Vector2(%.4f, %.4f)" % (a, b) for a, b in r))
    out.append("]")
    out.append("## The clips cut from those rows: one ROW of this per hull")
    out.append("## weight, indexed by HullData.Weight, and one COLUMN per")
    out.append("## pattern above. Same flame timing at every weight -- what")
    out.append("## changes across a row is how big the engine making it is.")
    out.append("##")
    out.append("## Not named `thruster_arrive_2`: Audio.play() reads that")
    out.append("## spelling as a round-robin take and would pick one at")
    out.append("## random, which is exactly the desynchronisation this table")
    out.append("## exists to prevent.")
    out.append("const FLAMEOUT_SFX := [")
    for w, _rate, _tilt, _a, _dr in WEIGHTS:
        out.append("	[%s],  ## %s"
                   % (", ".join('&"thruster_arrive_%s_%s"' % (w, n)
                                for n in NAMES), w.upper()))
    out.append("]")
    out.append("## And the drive coming UP, one per weight. No pattern here:")
    out.append("## nothing is gated, so there is nothing to stay in step with.")
    out.append("const DEPART_SFX: Array[StringName] = [%s]"
               % ", ".join('&"thruster_depart_%s"' % w
                           for w, _r, _t, _a, _d in WEIGHTS))
    out.append(TAIL)
    body = "\n".join(out)

    s = io.open(SHIPVIEW, encoding="utf-8", newline="").read()
    if HEAD not in s or TAIL not in s:
        raise SystemExit("ShipView.gd has lost its markers; put them back "
                         "before running this")
    start = s.index(HEAD)
    end = s.index(TAIL) + len(TAIL)
    io.open(SHIPVIEW, "w", encoding="utf-8",
            newline="").write(s[:start] + body + s[end:])


def render():
    rows = build()
    write_gd(rows)
    src = roar()
    total = 0.0
    for weight, rate, tilt, a_db, drive in WEIGHTS:
        for name, r in zip(NAMES, rows):
            st = cut(src, r, rate0=rate, tilt_db=tilt, a_db=a_db, drive=drive)
            path = os.path.join(SFX, "thruster_arrive_%s_%s.wav"
                                % (weight, name))
            synth.write_wav(path, st)
            kb = os.path.getsize(path) / 1024.0
            total += kb
            lens = " ".join("%3.0f" % ((b - a) * ARRIVE_S * 1000.0)
                            for a, b in r[1:])
            print("  %-6s %s  burn %4.2f  out %4.2f  %d coughs  %4.2fs "
                  "%5.0f KB   ms: %s"
                  % (weight, name, r[0][1], r[-1][1], len(r) - 1,
                     st.shape[1] / SR, kb, lens))
    for weight, rate, tilt, a_db, drive in WEIGHTS:
        st = spool(src, rate0=rate, tilt_db=tilt,
                   a_db=a_db + DEPART_A_TRIM, drive=drive)
        path = os.path.join(SFX, "thruster_depart_%s.wav" % weight)
        synth.write_wav(path, st)
        kb = os.path.getsize(path) / 1024.0
        total += kb
        print("  %-6s depart  spool %.2fx -> %.2fx  %4.2fs %5.0f KB"
              % (weight, rate * SPOOL_FROM, rate * SPOOL_TO,
                 st.shape[1] / SR, kb))
    print("  %d clips, %.1f MB of wav (QOA on import, so roughly a third of "
          "that ships)" % (len(WEIGHTS) * len(NAMES), total / 1024.0))
    return rows


if __name__ == "__main__":
    render()
    sys.exit(0)
