"""The foley palette: raw MATERIAL for sfx2.py, generated by Stable Audio.

Not finished sounds -- ingredients.  sfx2 layers these under pitched glue
the way the music layers recorded instruments under the motif.  Palette is
regenerable (fixed seeds) and lives in samples/ with the other build-only
material; the game ships renders, never these.
"""
import torch, soundfile as sf, os, time
import gen_sfx  # noise-sampler patch
from diffusers import StableAudioPipeline

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'samples', 'foley')
PALETTE = [
    ('click_mech',  'single small mechanical switch click, dry, close', 1.0),
    ('latch',       'small metal latch snapping shut, single event, dry', 1.0),
    ('servo_move',  'small electric servo motor moving briefly, robotic arm', 1.5),
    ('air_hiss',    'short pressurized air release hiss, valve', 1.5),
    ('metal_small', 'small metal part dropped on a metal bench, single', 1.0),
    ('metal_big',   'heavy sheet metal impact with a metallic ring, single', 2.0),
    ('debris',      'small metal debris scattering and settling after impact', 2.5),
    ('boom_deep',   'deep distant explosion boom, single, no music', 2.5),
    ('whoosh',      'fast air whoosh passing by, single', 1.5),
    ('paper_slide', 'single sheet of paper sliding on a wooden desk', 1.2),
    ('static_tick', 'tiny electric spark tick, static discharge, single', 0.8),
    ('rumble',      'low mechanical rumble, engine room, short', 2.5),
    ('card_snap',   'playing card snapped down onto a table, single', 1.0),
    ('ratchet',     'small ratchet wrench single click turn', 1.0),
    ('steam_puff',  'short steam puff release, single chuff', 1.2),
]

if __name__ == '__main__':
    os.makedirs(OUT, exist_ok=True)
    pipe = StableAudioPipeline.from_pretrained(
        "stabilityai/stable-audio-open-1.0",
        torch_dtype=torch.float32).to("mps")
    for name, prompt, secs in PALETTE:
        dst = os.path.join(OUT, name + '.wav')
        if os.path.exists(dst):
            print('skip', name); continue
        t0 = time.time()
        g = torch.Generator("cpu").manual_seed(hash(name) % 2**31)
        a = pipe(prompt, negative_prompt="music, melody, reverb, low quality",
                 num_inference_steps=100, audio_end_in_s=secs,
                 generator=g).audios[0]
        sf.write(dst, a.T.float().cpu().numpy(), pipe.vae.sampling_rate)
        print('%s: %.1fs gen' % (name, time.time() - t0))
