class_name BoardScreen
extends RefCounted
## WHAT A CITY'S AND A CAPITAL'S MARKETPLACE SCREEN SHOWS, besides the work: a
## pool to pick from (Jon: "Not 20X on the board, just a big pool to pick from
## for diversity"). `PostingBoard` starts each station at its own place in each
## list, by the station's number, and turns them over on the clock, so two
## screens side by side are not showing the same ad.
##
## Text is the Silkscreen pixel font, upper case. An ad's lines are [words,
## size] with size 16 (big) or 8 (small); a big line holds about 7 letters
## across an ad, a small one about 14. A strip ad's two lines hold about 30.
## A popup's body lines hold about 15.
##
## Measured since, for the long lists: an ad panel is about 104 wide and 170
## tall, each line taking its size and 6 more, so keep a big line to 6 letters,
## a small one to 15, and the lines to about 150 tall in all. A strip is about
## 240 wide: its lines hold 36. A popup is 176 wide: its title holds 22, its
## body lines 24 (two or three of them), its button 10. A listing's title
## holds 20, a headline 40, a stamp 9.

const ADS := [
	{"bg": Color("#f0c040"), "ink": Color("#2a1a08"), "lines": [["HULL", 16], ["WAX", 16], ["SHINE LIKE", 8], ["NEW!", 8], ["2 FOR 1", 16]]},
	{"bg": Color("#1e5ec8"), "ink": Color("#ffffff"), "lines": [["CHEAP", 16], ["COVER", 16], ["NO", 8], ["QUESTIONS*", 8], ["", 8], ["*SOME", 8], ["QUESTIONS", 8]]},
	{"bg": Color("#c83a7a"), "ink": Color("#fff0f6"), "lines": [["LONELY", 16], ["IN THE", 8], ["VOID?", 16], ["PEN PALS", 8], ["4 CR", 16]]},
	{"bg": Color("#14161c"), "ink": Color("#f0e040"), "lines": [["HOT", 16], ["PODS", 16], ["IN YOUR", 8], ["AREA", 16], ["", 8], ["ESCAPE PODS", 8], ["FOR SALE", 8]]},
	{"bg": Color("#3ec8e0"), "ink": Color("#061426"), "lines": [["COLD", 16], ["SLEEP", 16], ["PODS", 16], ["WAKE UP", 8], ["RICHER*", 8], ["", 8], ["*NOT A", 8], ["PROMISE", 8]]},
	{"bg": Color("#c8282a"), "ink": Color("#fff4d0"), "lines": [["KORVAN", 16], ["SURPLUS", 8], ["IT FIRES.", 8], ["MOSTLY.", 8], ["-40%", 16]]},
	{"bg": Color("#a8f0d0"), "ink": Color("#0a3a2a"), "lines": [["DRONE", 16], ["SPA", 16], ["THEY", 8], ["DESERVE", 8], ["IT TOO", 8], ["9 CR", 16]]},
	{"bg": Color("#5a3ac8"), "ink": Color("#f4f0ff"), "lines": [["NEW!", 16], ["HULL", 16], ["SCENT", 16], ["SMELLS", 8], ["LIKE", 8], ["NOTHING", 8]]},
	{"bg": Color("#ff8a6a"), "ink": Color("#2a0a08"), "lines": [["GOT", 16], ["SCRAP?", 16], ["WE PAY", 8], ["CASH FOR", 8], ["ANY OLD", 8], ["JUNK", 16]]},
	{"bg": Color("#0e6a6a"), "ink": Color("#e0fff8"), "lines": [["SLIM", 16], ["DOWN", 16], ["YOUR", 16], ["HULL", 16], ["LOSE 9 TONS", 8], ["IN ONE JUMP", 8]]},
	{"bg": Color("#f0c040"), "ink": Color("#6a1010"), "lines": [["NOODLE", 16], ["BAR", 16], ["DECK 3", 8], ["OPEN ALL", 8], ["CYCLE", 8], ["LONG", 8]]},
	{"bg": Color("#2a0a4a"), "ink": Color("#ff60c0"), "lines": [["TIRED", 16], ["OF", 8], ["JUMPS?", 16], ["TRY", 8], ["SITTING", 8], ["STILL", 16]]},
	{"bg": Color("#a8e040"), "ink": Color("#142008"), "lines": [["LUCKY", 16], ["CORE", 16], ["FOUND IN", 8], ["A WRECK", 8], ["NOT", 8], ["CURSED", 16]]},
	{"bg": Color("#0a1e4a"), "ink": Color("#ff9a3a"), "lines": [["RENT", 16], ["A", 8], ["CREW", 16], ["BY THE", 8], ["HOUR", 16], ["NO", 8], ["SINGING", 8]]},
	{"bg": Color("#f4f0e8"), "ink": Color("#c82a2a"), "lines": [["RUNNING", 8], ["HOT?", 16], ["SOLARI", 16], ["SAYS", 8], ["THAT IS", 8], ["FINE", 16]]},
	{"bg": Color("#16202e"), "ink": Color("#58c8d8"), "lines": [["NEVER", 16], ["ALONE", 16], ["CYGNET", 8], ["DRONES", 8], ["WATCH YOU", 8], ["SLEEP", 16]]},
	{"bg": Color("#e040c0"), "ink": Color("#1a0618"), "lines": [["WILLS", 16], ["FOR", 8], ["PILOTS", 16], ["LEAVE", 8], ["YOUR SHIP", 8], ["TO US", 8], ["", 8], ["PROBATE", 8], ["COMBINE", 8]]},
	{"bg": Color("#6a3a1a"), "ink": Color("#ffd890"), "lines": [["SUIT", 16], ["PATCH", 16], ["ONE SIZE", 8], ["FITS MOST", 8], ["HOLES", 8], ["2 CR", 16]]},
	{"bg": Color("#8ac8ff"), "ink": Color("#0a1a3a"), "lines": [["LAST", 16], ["JUMP", 16], ["SALE", 16], ["ALL MUST GO", 8], ["", 8], ["(SO MUST", 8], ["WE)", 8]]},
	{"bg": Color("#0a3a1a"), "ink": Color("#a8ff60"), "lines": [["HEAT", 16], ["RASH?", 16], ["ASK ABOUT", 8], ["COLD GEL", 8], ["3 CR", 16]]},
	{"bg": Color("#fff0b0"), "ink": Color("#1e5ec8"), "lines": [["REWARD", 16], ["FOR", 8], ["BLIP", 16], ["SMALL DRONE", 8], ["BEEPS A LOT", 8], ["", 8], ["DECK 6", 8]]},
	{"bg": Color("#b81e1e"), "ink": Color("#ffffff"), "lines": [["WRECK", 16], ["TOURS", 16], ["SEE WHERE", 8], ["THEY WENT", 8], ["WRONG", 16]]},
	{"bg": Color("#c8a020"), "ink": Color("#1a1404"), "lines": [["BIG", 16], ["HOLD", 16], ["SMALL", 16], ["PRICE", 16], ["HAULER", 8], ["FOR RENT", 8]]},
	{"bg": Color("#101010"), "ink": Color("#ff4a4a"), "lines": [["SWARM", 16], ["SEEN?", 16], ["CALL", 8], ["DOCK WATCH", 8], ["", 8], ["(WE WILL", 8], ["NOT COME)", 8]]},
	{"bg": Color("#1a6a3a"), "ink": Color("#f0fff0"), "lines": [["DEBT?", 16], ["LET US", 8], ["HOLD IT", 8], ["FOR YOU", 8], ["", 8], ["9% A DAY", 8]]},
	{"bg": Color("#ff3aa0"), "ink": Color("#1a0618"), "lines": [["GRAV", 16], ["SOCKS", 16], ["STAY ON", 8], ["YOUR FEET", 8], ["3 PAIRS", 8], ["5 CR", 16]]},
	{"bg": Color("#14161c"), "ink": Color("#40f0ff"), "lines": [["FAST", 16], ["JUMPS", 16], ["SLOW", 16], ["SNACKS", 16], ["DECK 2", 8], ["DINER", 8]]},
	{"bg": Color("#e0702a"), "ink": Color("#1a0a00"), "lines": [["FORMS", 16], ["FILLED", 16], ["WE DO THE", 8], ["DOCK PAPERS", 8], ["FOR YOU", 8], ["IN PEN", 8]]},
	{"bg": Color("#1e5ec8"), "ink": Color("#ffe040"), "lines": [["PET", 16], ["ROCK", 16], ["FROM", 8], ["A REAL", 8], ["COMET", 16], ["10 CR", 8]]},
	{"bg": Color("#f4f0e8"), "ink": Color("#14161c"), "lines": [["HULL", 16], ["DENTS", 16], ["POPPED OUT", 8], ["WHILE", 8], ["YOU", 8], ["WAIT", 16]]},
	{"bg": Color("#5a1a6a"), "ink": Color("#ffd0ff"), "lines": [["SLEEP", 16], ["IN", 8], ["ORBIT", 16], ["CABINS", 8], ["FROM", 8], ["2 CR", 16], ["WINDOW", 8], ["EXTRA", 8]]},
	{"bg": Color("#a8f0d0"), "ink": Color("#3a0a2a"), "lines": [["MOM'S", 16], ["SOUP", 16], ["JUST LIKE", 8], ["MOM USED", 8], ["TO BUY", 8]]},
	{"bg": Color("#e8e0cc"), "ink": Color("#5a4a20"), "lines": [["VERITY", 16], ["MADE", 8], ["ONCE", 16], ["PRICED", 8], ["TWICE", 16]]},
	{"bg": Color("#1c2127"), "ink": Color("#ff6a5a"), "lines": [["STILL", 16], ["FLYING?", 8], ["REDLINE", 8], ["REFITS", 16], ["NO PAPERS", 8], ["NEEDED", 8]]},
	{"bg": Color("#40e0a0"), "ink": Color("#062018"), "lines": [["ASK", 16], ["ABOUT", 16], ["OUR", 16], ["DEALS", 16], ["", 8], ["(WE HAVE", 8], ["NONE)", 8]]},
	{"bg": Color("#3a1a08"), "ink": Color("#ff9a3a"), "lines": [["LEARN", 16], ["TO", 8], ["WELD", 16], ["IN ONE", 8], ["SHIFT", 16], ["BRING", 8], ["GLOVES", 8]]},
	{"bg": Color("#ffffff"), "ink": Color("#1a1a1a"), "lines": [["YOUR", 16], ["AD", 16], ["HERE", 16], ["", 8], ["ONLY 3 CR", 8], ["A DAY", 8]]},
	{"bg": Color("#0a1e4a"), "ink": Color("#c8f0ff"), "lines": [["ICE", 16], ["FROM", 8], ["REAL", 8], ["RINGS", 16], ["CHIPPED", 8], ["TO ORDER", 8]]},
	{"bg": Color("#f0c040"), "ink": Color("#1e3a8a"), "lines": [["KIDS", 16], ["FLY", 16], ["FREE", 16], ["WITH ONE", 8], ["PAYING", 8], ["ADULT", 8]]},
	{"bg": Color("#a82020"), "ink": Color("#fff0b0"), "lines": [["TIME", 16], ["SHARE", 16], ["ON A", 8], ["MOON", 16], ["", 8], ["NEVER", 8], ["VISIT IT", 8]]},
	{"bg": Color("#8ac8ff"), "ink": Color("#3a0a2a"), "lines": [["MOVING", 16], ["DECKS?", 16], ["WE CARRY", 8], ["THE BOXES", 8], ["UP STAIRS", 8]]},
	{"bg": Color("#0e6a6a"), "ink": Color("#ffe040"), "lines": [["EYE", 16], ["DROPS", 16], ["FOR", 8], ["STAR GLARE", 8], ["2 CR", 16]]},
	{"bg": Color("#3a2408"), "ink": Color("#ef9f27"), "lines": [["HEAT", 16], ["LAMPS", 16], ["FOR", 8], ["COLD BUNKS", 8], ["", 8], ["BY SOLARI", 8], ["FOUNDRY", 8]]},
	{"bg": Color("#ff8a6a"), "ink": Color("#14161c"), "lines": [["YARD", 16], ["SALE", 16], ["DOCK 9", 8], ["HULLS", 8], ["HALF", 8], ["BUILT", 8]]},
	{"bg": Color("#2a0a4a"), "ink": Color("#ffe040"), "lines": [["NAME", 16], ["A", 8], ["STAR", 16], ["AFTER", 8], ["SOMEONE", 8], ["YOU LOVE", 8], ["1 CR", 16]]},
	{"bg": Color("#e2ece6"), "ink": Color("#1e5a3a"), "lines": [["CALYX", 16], ["HOME", 16], ["MOSS", 16], ["MAKES AIR", 8], ["MAKES", 8], ["FRIENDS", 8]]},
	{"bg": Color("#c8282a"), "ink": Color("#ffffff"), "lines": [["FIRE", 16], ["SALE", 16], ["THE SHOP", 8], ["IS ON FIRE", 8], ["HURRY", 16]]},
	{"bg": Color("#a8e040"), "ink": Color("#2a0a4a"), "lines": [["ZERO G", 16], ["SPIN", 16], ["CLASS", 16], ["NOBODY", 8], ["KNOWS WHICH", 8], ["WAY IS UP", 8]]},
	{"bg": Color("#101010"), "ink": Color("#ff9a3a"), "lines": [["LIVE", 16], ["BAND", 16], ["THE", 8], ["COUPLINGS", 8], ["FRI", 8], ["DECK 6", 8]]},
	{"bg": Color("#3ec8e0"), "ink": Color("#3a0a2a"), "lines": [["WHY", 16], ["RENT?", 16], ["BUY A", 8], ["BUNK", 16], ["30 YEAR", 8], ["PLANS", 8]]},
	{"bg": Color("#5a3ac8"), "ink": Color("#ffe040"), "lines": [["SEE", 16], ["THE", 8], ["SWARM", 16], ["UP", 8], ["CLOSE", 16], ["TOURS", 8], ["ONE WAY", 8]]},
	{"bg": Color("#fff0b0"), "ink": Color("#b81e1e"), "lines": [["SHIP", 16], ["NAMES", 16], ["PAINTED", 8], ["BY HAND", 8], ["", 8], ["SPELLED", 8], ["RIGHT EXTRA", 8]]},
	{"bg": Color("#0a3a1a"), "ink": Color("#ffffff"), "lines": [["SPARE", 16], ["AIR", 16], ["TANKS", 16], ["FULL!", 8], ["OR NEARLY", 8]]},
	{"bg": Color("#e040c0"), "ink": Color("#1a0618"), "lines": [["BEST", 16], ["PILOT", 16], ["MUGS", 16], ["SPILL", 8], ["PROOF*", 8], ["", 8], ["*NOT IN", 8], ["SPACE", 8]]},
	{"bg": Color("#14161c"), "ink": Color("#a8ff60"), "lines": [["VOTE", 16], ["NO", 16], ["ON DOCK", 8], ["FEE 12", 8], ["", 8], ["IT IS", 8], ["ALREADY LAW", 8]]},
	{"bg": Color("#f4f0e8"), "ink": Color("#1e5ec8"), "lines": [["DOCK", 16], ["MUSIC", 16], ["8 HOURS", 8], ["OF HOLD", 8], ["TUNES", 8], ["ON TAPE", 8]]},
	{"bg": Color("#6a1a1a"), "ink": Color("#ffd890"), "lines": [["FACE", 16], ["SCAN", 16], ["PHOTOS", 8], ["NOW WITH", 8], ["GOOD SIDE", 8], ["5 CR", 16]]},
	{"bg": Color("#40e0a0"), "ink": Color("#1a0618"), "lines": [["GROW", 16], ["YOUR", 16], ["OWN", 16], ["AIR", 16], ["KITS FROM", 8], ["12 CR", 8]]},
	{"bg": Color("#10245a"), "ink": Color("#ff8a6a"), "lines": [["JUMP", 16], ["SICK?", 16], ["CHEW", 8], ["THESE", 8], ["", 8], ["DO NOT ASK", 8], ["WHAT THEY", 8], ["ARE", 8]]},
	{"bg": Color("#c8a020"), "ink": Color("#2a0a4a"), "lines": [["FREE", 16], ["HAT", 16], ["WITH ANY", 8], ["HULL OVER", 8], ["90K CR", 16]]},
	{"bg": Color("#b81e1e"), "ink": Color("#f0e040"), "lines": [["TOW", 16], ["AND", 8], ["GO", 16], ["WE BRING", 8], ["IT BACK", 8], ["IN SOME", 8], ["FORM", 8]]},
]

const STRIPS := [
	{"bg": Color("#2a9a5a"), "ink": Color("#f0fff0"), "t": "JUMP INSURANCE", "s": "NOBODY HAS EVER CLAIMED"},
	{"bg": Color("#e0702a"), "ink": Color("#fff4e8"), "t": "SPARE PARTS DEPOT", "s": "DECK 4, NEXT TO THE NOODLES"},
	{"bg": Color("#5a3ac8"), "ink": Color("#f4f0ff"), "t": "LEARN TO JUMP", "s": "FIRST LESSON FREE*"},
	{"bg": Color("#14161c"), "ink": Color("#f0e040"), "t": "DOCK PARKING", "s": "FIRST HOUR FREE, NEXT HOUR 90 CR"},
	{"bg": Color("#8ac8ff"), "ink": Color("#0a1a3a"), "t": "COLD SLEEP CLINIC", "s": "WE WAKE YOU UP. MOST TIMES."},
	{"bg": Color("#5a2a0a"), "ink": Color("#ffe8c0"), "t": "KORVAN SURPLUS", "s": "IT FIRES. EVERY TIME. LOUDLY."},
	{"bg": Color("#f0c040"), "ink": Color("#2a1a08"), "t": "LOST IN THE LAYERS?", "s": "MAPS 3 CR, WRONG ONES 1 CR"},
	{"bg": Color("#16202e"), "ink": Color("#58c8d8"), "t": "CYGNET DRONE CARE", "s": "YOU ARE NEVER ALONE. EVEN IN THE BATH"},
	{"bg": Color("#ef9f27"), "ink": Color("#2a1404"), "t": "SOLARI HEAT PLATES", "s": "RUN HOT. STAY HOT. KEEP RUNNING."},
	{"bg": Color("#0a3a1a"), "ink": Color("#a8ff60"), "t": "THE PROBATE COMBINE", "s": "WE BUY WRECKS. AND WE WAIT."},
	{"bg": Color("#901414"), "ink": Color("#ffffff"), "t": "SEEN THE HELLBENDER?", "s": "DO NOT TELL US. TELL THE BOUNTY DESK"},
	{"bg": Color("#e8e0cc"), "ink": Color("#4a3a10"), "t": "VERITY ATELIERS", "s": "ONE HULL A YEAR. WAIT LIST: 40 YEARS"},
	{"bg": Color("#1e5a3a"), "ink": Color("#e2ece6"), "t": "CALYX GREEN ROOMS", "s": "FRESH AIR, GROWN TODAY"},
	{"bg": Color("#1c2127"), "ink": Color("#ff9a8a"), "t": "REDLINE REFITS", "s": "NO PAPERS. NO QUESTIONS."},
	{"bg": Color("#fff0b0"), "ink": Color("#b81e1e"), "t": "FRESH NOODLES", "s": "DECK 3, WHERE THE STEAM IS"},
	{"bg": Color("#2a0a4a"), "ink": Color("#ff60c0"), "t": "SWARM SEASON SALE", "s": "ARMOUR UP 20%, PRICES UP 40%"},
	{"bg": Color("#3ec8e0"), "ink": Color("#061426"), "t": "SPEED DATING FOR PILOTS", "s": "TWO MINUTES, THEN YOU JUMP"},
	{"bg": Color("#0a1e4a"), "ink": Color("#ff9a3a"), "t": "HAUL IT YOURSELF", "s": "TRUCK HIRE BY THE DECK"},
	{"bg": Color("#a8e040"), "ink": Color("#142008"), "t": "WELDING CLASS, DECK 7", "s": "BRING GLOVES. BRING EYEBROWS."},
	{"bg": Color("#5a1a6a"), "ink": Color("#ffd0ff"), "t": "HULL WAX CLUB", "s": "JOIN FREE, LEAVE FOR 50 CR"},
	{"bg": Color("#f4f0e8"), "ink": Color("#1e3a8a"), "t": "TRADE IN YOUR OLD HULL", "s": "WE TAKE ANYTHING THAT HOLDS AIR"},
	{"bg": Color("#0e4a4a"), "ink": Color("#e0fff8"), "t": "STATION BANK", "s": "YOUR CREDITS ARE SAFE. MOSTLY."},
	{"bg": Color("#ff8a6a"), "ink": Color("#2a0a08"), "t": "GOT HEAT?", "s": "WE VENT ANY SHIP IN 10 MINUTES"},
	{"bg": Color("#101010"), "ink": Color("#ff60c0"), "t": "THE NIGHT MARKET", "s": "DECK 9, AFTER THE LIGHTS GO DIM"},
	{"bg": Color("#c8a020"), "ink": Color("#1a1404"), "t": "SECOND HAND SUITS", "s": "ONE OWNER, BARELY BREATHED IN"},
	{"bg": Color("#1e3a8a"), "ink": Color("#ffe040"), "t": "LEARN TO HAUL", "s": "NO LICENCE NEEDED, JUST A SHIP"},
	{"bg": Color("#a8f0d0"), "ink": Color("#0a3a2a"), "t": "DECK 5 BATHS", "s": "HOT WATER ON TUESDAYS ONLY"},
	{"bg": Color("#6a1a1a"), "ink": Color("#ffd890"), "t": "RENT A DRONE", "s": "IT WILL JUDGE YOU QUIETLY"},
	{"bg": Color("#e040c0"), "ink": Color("#1a0618"), "t": "TONIGHT: CRATE RACING", "s": "BET ON A BOX. LOSE TO A BOX."},
	{"bg": Color("#14161c"), "ink": Color("#40f0ff"), "t": "AIR TAX REFUNDS", "s": "YOU BREATHED LESS? PROVE IT."},
	{"bg": Color("#fff0b0"), "ink": Color("#3a2408"), "t": "OLD STAR CHARTS", "s": "SOME OF THESE STARS ARE STILL THERE"},
	{"bg": Color("#3a3e48"), "ink": Color("#ffffff"), "t": "SALVAGE RIGHTS OFFICE", "s": "TAKE A NUMBER. NOW TAKE A SEAT."},
	{"bg": Color("#40e0a0"), "ink": Color("#062018"), "t": "PILOT EYE TESTS", "s": "READ THE TOP LINE. GOOD. YOU PASS."},
	{"bg": Color("#2a0a4a"), "ink": Color("#ffe040"), "t": "BUNK SWAP BOARD", "s": "TOP FOR BOTTOM, NO SNORERS"},
	{"bg": Color("#f0c040"), "ink": Color("#6a1010"), "t": "THE CORE EXCHANGE", "s": "BUY LOW, SELL TO YOUR COUSIN"},
	{"bg": Color("#3a1a08"), "ink": Color("#ff9a3a"), "t": "DOCK 2 CAFE", "s": "COFFEE AS HOT AS YOUR REACTOR"},
	{"bg": Color("#8ac8ff"), "ink": Color("#3a0a2a"), "t": "CHEAP JUMPS!", "s": "TO PLACES ALMOST WHERE YOU WANTED"},
	{"bg": Color("#0a3a1a"), "ink": Color("#ffffff"), "t": "HULL PAINT, ANY COLOUR", "s": "AS LONG AS IT IS GREY"},
	{"bg": Color("#ff3aa0"), "ink": Color("#1a0618"), "t": "YOUR SHIP, NOW TALKING", "s": "VOICE PACKS FROM 5 CR"},
	{"bg": Color("#0a1e4a"), "ink": Color("#c8f0ff"), "t": "INSURE YOUR DRONE", "s": "BECAUSE IT WILL TRY TO LEAVE"},
	{"bg": Color("#e0702a"), "ink": Color("#1a0a00"), "t": "LOOKING FOR CREW?", "s": "WE HAVE 4. ONE OF THEM IS GOOD."},
	{"bg": Color("#e2ece6"), "ink": Color("#1e5a3a"), "t": "PLANT SITTING", "s": "WE WATER IT. WE TALK TO IT."},
	{"bg": Color("#101010"), "ink": Color("#a8ff60"), "t": "SCRAP WEIGH STATION", "s": "OUR SCALES ARE HONEST ON MONDAYS"},
	{"bg": Color("#7a1414"), "ink": Color("#fff0b0"), "t": "RECYCLED WATER", "s": "NOW 90% LESS RECYCLED TASTE"},
	{"bg": Color("#3ec8e0"), "ink": Color("#2a0a4a"), "t": "GRAV BOOTS, 2 FOR 1", "s": "LEFT AND RIGHT SOLD APART"},
	{"bg": Color("#16202e"), "ink": Color("#f0c040"), "t": "STATION RADIO 88", "s": "ALL HULL NEWS, ALL THE TIME"},
	{"bg": Color("#f4f0e8"), "ink": Color("#c82a2a"), "t": "PHOTOS WITH A REAL* COMET", "s": "*PAINTED ON A WALL"},
	{"bg": Color("#5a3ac8"), "ink": Color("#ffffff"), "t": "THE SWARM IS COMING", "s": "GOOD TIME TO BUY A BIGGER GUN"},
	{"bg": Color("#a8e040"), "ink": Color("#2a0a4a"), "t": "DOCK LOCKERS", "s": "WE LOST THE KEYS. SPECIAL PRICE."},
	{"bg": Color("#0e4a4a"), "ink": Color("#ffe040"), "t": "QUIET CABINS", "s": "NO ENGINES. NO NEIGHBOURS. NO DOOR."},
	{"bg": Color("#ff8a6a"), "ink": Color("#14161c"), "t": "ESCAPE POD CHECKS", "s": "IS YOURS REAL? MANY ARE NOT."},
	{"bg": Color("#1e5a3a"), "ink": Color("#fff0b0"), "t": "FIND YOUR FAMILY", "s": "WE SEARCH 40 STATIONS FOR 2 CR"},
	{"bg": Color("#14161c"), "ink": Color("#ff7a7a"), "t": "BIG HEAT, BIG SALE", "s": "EVERY COOLANT MUST GO. FAST."},
	{"bg": Color("#ffffff"), "ink": Color("#5a1a6a"), "t": "PEN PALS IN THE VOID", "s": "WE WRITE BACK EVERY 3 YEARS"},
	{"bg": Color("#b81e1e"), "ink": Color("#ffffff"), "t": "HULL BALL FINAL", "s": "DOCKS VS DECKS. SOLD OUT. AGAIN."},
	{"bg": Color("#c8a020"), "ink": Color("#2a0a4a"), "t": "FORGET THAT LAST JUMP", "s": "MEMORY PARLOUR, DECK 8, 7 CR"},
	{"bg": Color("#1e3a8a"), "ink": Color("#ffffff"), "t": "FREE HUGS", "s": "4 CR"},
	{"bg": Color("#f0c040"), "ink": Color("#1e3a8a"), "t": "SPARE AIR TANKS", "s": "FULL! OR AT LEAST NOT EMPTY."},
	{"bg": Color("#3a2408"), "ink": Color("#ef9f27"), "t": "CRASH PADS", "s": "SOFT LANDINGS FOR SOFT PILOTS"},
	{"bg": Color("#a8f0d0"), "ink": Color("#3a0a2a"), "t": "SHIP SITTERS", "s": "WE WATCH IT. WE DO NOT FLY IT. MUCH."},
]

const POPUPS := [
	{"title": "WINNER!", "body": ["YOU WON A", "FREE JUMP!"], "btn": "CLAIM"},
	{"title": "WARNING", "body": ["3 VIRUSES ON", "YOUR HULL"], "btn": "SCAN NOW"},
	{"title": "OFFER", "body": ["FUEL PRICES", "HATE HIM"], "btn": "SEE WHY"},
	{"title": "ALERT", "body": ["YOUR HULL WARRANTY", "HAS RUN OUT"], "btn": "RENEW"},
	{"title": "CONGRATULATIONS", "body": ["YOU ARE VISITOR", "1,000,000!"], "btn": "CLAIM"},
	{"title": "LOW AIR", "body": ["JUST KIDDING.", "BUY MORE AIR ANYWAY."], "btn": "BUY AIR"},
	{"title": "NEW FOLLOWER", "body": ["A HAULER YOU PASSED", "IS NOW FOLLOWING YOU"], "btn": "BLOCK"},
	{"title": "ONE ODD TRICK", "body": ["SHE JUMPS FOR FREE.", "DOCK FEES HATE HER."], "btn": "LEARN"},
	{"title": "SURVEY", "body": ["HOW WAS YOUR LAST", "JUMP? 1 TO 5 STARS"], "btn": "RATE"},
	{"title": "UPDATE READY", "body": ["THIS SCREEN WILL", "RESTART IN 3 JUMPS"], "btn": "LATER"},
	{"title": "DOCK NOTICE", "body": ["YOUR SHIP IS PARKED", "IN A NO JUMP ZONE"], "btn": "PAY FINE"},
	{"title": "LAST CHANCE", "body": ["HULL WAX 2 FOR 1", "ENDS IN 0 SECONDS"], "btn": "HURRY"},
	{"title": "FRIEND REQUEST", "body": ["THE HELLBENDER WANTS", "TO BE FRIENDS"], "btn": "ACCEPT"},
	{"title": "HEADS UP", "body": ["A DRONE IS LOOKING", "AT YOUR LISTING"], "btn": "WAVE"},
	{"title": "MESSAGE (1)", "body": ["HI, I AM A PRINCE OF", "THE OUTER RING. I NEED", "YOUR DOCK CODE."], "btn": "REPLY"},
	{"title": "QUICK QUESTION", "body": ["ARE YOU STILL", "IN THE VOID?"], "btn": "YES"},
	{"title": "COOKIES", "body": ["THIS SCREEN USES", "REAL COOKIES. DECK 3."], "btn": "YUM"},
	{"title": "SWARM ALERT", "body": ["NOTHING IS WRONG.", "PLEASE KEEP SHOPPING."], "btn": "SHOP"},
	{"title": "YOU ARE HOT", "body": ["YOUR HEAT IS AT 98%.", "WE SELL COOLANT."], "btn": "COOL OFF"},
	{"title": "SPIN TO WIN", "body": ["EVERY SPIN WINS!*", "", "*A SPIN"], "btn": "SPIN"},
	{"title": "BILL DUE", "body": ["YOU OWE 0.02 CR", "FOR LOOKING AT THIS"], "btn": "PAY"},
	{"title": "RATE YOUR DRONE", "body": ["IT ALREADY RATED", "YOU 2 STARS"], "btn": "ARGUE"},
	{"title": "SAFE SHOPPING", "body": ["THIS LISTING IS", "99% NOT A SCAM"], "btn": "TRUST"},
	{"title": "SIGN IN", "body": ["PLEASE ENTER YOUR", "NAME, SHIP AND", "FIRST HULL'S NAME"], "btn": "SIGN IN"},
	{"title": "ERROR", "body": ["SOMETHING WENT RIGHT.", "WE ARE LOOKING INTO IT."], "btn": "OK"},
	{"title": "NEW ON DECK 4", "body": ["A NOODLE STAND", "THAT SELLS NOODLES"], "btn": "WOW"},
	{"title": "SALE!", "body": ["EVERYTHING 50% OFF", "OF DOUBLE PRICE"], "btn": "BUY"},
	{"title": "ARE YOU A PILOT?", "body": ["CLICK EVERY BOX", "WITH A STAR IN IT"], "btn": "CHECK"},
	{"title": "JUMP DELAYED", "body": ["YOUR JUMP IS", "DELAYED BY 1 YEAR"], "btn": "FINE"},
	{"title": "FREE HULL SCAN", "body": ["WE FOUND 12 DENTS", "ON YOUR HULL"], "btn": "FIX ALL"},
	{"title": "CHAT", "body": ["HELLO? IS THIS SHIP", "STILL FOR SALE?"], "btn": "REPLY"},
	{"title": "KORVAN NEWS", "body": ["RECALLED COUPLINGS", "ARE NOW COLLECTIBLE"], "btn": "COLLECT"},
	{"title": "CYGNET SAYS HI", "body": ["YOU ARE NEVER ALONE.", "WE CHECKED."], "btn": "THANKS"},
	{"title": "SOLARI DEALS", "body": ["RUNNING HOT? RUN", "HOTTER. 10% OFF."], "btn": "IGNITE"},
	{"title": "CALYX TIP", "body": ["TALK TO YOUR HULL.", "IT IS GROWING."], "btn": "LISTEN"},
	{"title": "PROBATE NOTICE", "body": ["WE WILL BUY YOUR SHIP", "WHEN YOU ARE DONE", "WITH IT. AND YOU."], "btn": "WAIT"},
	{"title": "TIP OF THE DAY", "body": ["DO NOT JUMP INTO", "THE SUN."], "btn": "GOT IT"},
	{"title": "STATION POLL", "body": ["SHOULD DECK 7", "HAVE A DOOR?"], "btn": "VOTE"},
	{"title": "YOU HAVE MAIL", "body": ["IT IS FROM YOU,", "3 JUMPS AGO"], "btn": "OPEN"},
	{"title": "LIMITED OFFER", "body": ["ONLY 1 LEFT!", "(WE HAVE 900)"], "btn": "GRAB IT"},
	{"title": "HEY, YOU", "body": ["YES, YOU. YOU LOOK", "LIKE A HAULER."], "btn": "I AM"},
	{"title": "WIN A HULL", "body": ["GUESS HOW MANY BOLTS", "ARE IN THIS JAR"], "btn": "GUESS"},
	{"title": "AIR BILL", "body": ["YOU BREATHED 4%", "MORE THIS WEEK"], "btn": "PAY"},
	{"title": "LOST DRONE", "body": ["HAS ANYONE SEEN", "A SMALL DRONE? BLIP?"], "btn": "I HAVE"},
	{"title": "REMINDER", "body": ["YOUR DOCK SPOT ENDS", "IN 2 MINUTES"], "btn": "EXTEND"},
	{"title": "LUCKY DAY", "body": ["A FREE COUPLING IS", "WAITING ON DOCK 7"], "btn": "GO GET"},
	{"title": "DOWNLOAD MORE AIR", "body": ["FAST. SAFE.", "MOSTLY OXYGEN."], "btn": "GET"},
	{"title": "YOUR CART", "body": ["1 HULL WAX", "1 MORE HULL WAX"], "btn": "CHECK OUT"},
	{"title": "SHARE THIS", "body": ["TELL 5 FRIENDS OR", "YOUR REACTOR GETS SAD"], "btn": "SHARE"},
	{"title": "TERMS CHANGED", "body": ["BY READING THIS YOU", "AGREE TO HAUL A CRATE"], "btn": "AGREE"},
	{"title": "DEAR PILOT", "body": ["YOUR PEN PAL WROTE", "BACK! 4 CR TO READ"], "btn": "READ"},
	{"title": "HEAT WARNING", "body": ["THIS SCREEN IS WARM.", "PLEASE BLOW ON IT."], "btn": "BLOW"},
	{"title": "BOUNTY UPDATE", "body": ["THE HELLBENDER IS", "WORTH MORE TODAY"], "btn": "HUNT"},
	{"title": "JUST FOR YOU", "body": ["A JUMP TO NOWHERE,", "HALF PRICE"], "btn": "BOOK"},
	{"title": "MISSED CALL", "body": ["FROM: YOUR MOTHER", "SAYS: EAT SOMETHING"], "btn": "CALL BACK"},
	{"title": "LOW BATTERY", "body": ["THIS POPUP WILL", "CLOSE IN A MOMENT"], "btn": "STAY"},
	{"title": "QUIZ", "body": ["WHICH HULL ARE YOU?", "(IT IS A HAULER)"], "btn": "START"},
	{"title": "STRANGE LOGIN", "body": ["SOMEONE SIGNED IN", "FROM INSIDE YOUR HOLD"], "btn": "PANIC"},
	{"title": "DID YOU KNOW?", "body": ["DRONES DREAM.", "MOSTLY OF WALLS."], "btn": "WOW"},
	{"title": "DOCK 7 UPDATE", "body": ["STILL CLOSED FOR", "SCRUB. SORRY!"], "btn": "SIGH"},
]

## The news ticker's items; a station shows a run of them, joined by stars.
const TICKER := [
	"CORE PRICES UP 3%",
	"DOCK 7 CLOSED FOR SCRUB",
	"KORVAN RECALLS 400 COUPLINGS",
	"LOST: ONE DRONE, ANSWERS TO BLIP",
	"HULL WAX 2 FOR 1",
	"QUIET JUMP SEASON AHEAD",
	"NOODLES ON DECK 3 UNTIL LATE",
	"DOCK 4 REOPENS AFTER SCRUB",
	"COOLANT DOWN 2%, STILL TOO HIGH",
	"SWARM SEEN NEAR THE OUTER LAYERS",
	"HELLBENDER BOUNTY RAISED AGAIN",
	"FOUND: ONE GLOVE, LEFT, DECK 6",
	"LIFT B STUCK ON DECK 5, AGAIN",
	"SPACE WEATHER: COLD, DARK, ALL WEEK",
	"SOLAR WIND FROM THE LEFT, HOLD ON",
	"HULL BALL: DOCKS 3, DECKS 1",
	"CALYX MOSS NOW IN 40 CABINS",
	"CYGNET DRONES LEARN TO WAVE",
	"SOLARI PLANT RUNS HOT, AS PLANNED",
	"PROBATE COMBINE BUYS DOCK 9 SCRAP",
	"REDLINE SAYS IT WAS NEVER HERE",
	"VERITY SHIPS ONE HULL THIS YEAR",
	"KORVAN: RECALLED COUPLINGS FINE NOW",
	"AIR TAX UP HALF A CREDIT",
	"NOODLE PRICES STEADY ON DECK 3",
	"NEW BUNKS ON DECK 8, SAME SNORING",
	"LOST: CAT, ORANGE, ANSWERS TO NOTHING",
	"HAULER STRIKE ENDS AFTER ONE HOUR",
	"SCRAP PRICES FALL, SCRAP PILES RISE",
	"STATION TURNS 200, CAKE ON DECK 1",
	"DOCK 7 STILL CLOSED FOR SCRUB",
	"RECORD RUN: 9 LAYERS IN ONE DAY",
	"HEAT WAVE IN THE ENGINE BAYS",
	"SALVAGE RIGHTS OFFICE SHUT TODAY",
	"LIGHTS DIM AT 22:00 FOR NIGHT",
	"CORE PRICES DOWN 1%",
	"COUPLING SHORTAGE: HOLD ON TO YOURS",
	"MAYOR OPENS NEW BENCH ON DECK 5",
	"BENCH ON DECK 5 ALREADY TAKEN",
	"DRONE RACE MOVED TO DOCK 2",
	"WATER TASTES OF METAL, SAYS EVERYONE",
	"WATER TASTES FINE, SAYS WATER OFFICE",
	"FUEL CELLS UP AHEAD OF BUSY JUMPS",
	"QUIET NIGHT IN THE SHIPYARD",
	"NEW HULL WAX SMELLS OF LEMONS",
	"MISSING HAULER FOUND IN WRONG DOCK",
	"KIDS' WELDING CLASS FULL",
	"STAR CHARTS 2 YEARS OUT OF DATE",
	"PIRATES? NO, JUST A VERY LOUD HAULER",
	"FORECAST: NO RAIN, 100% VACUUM",
	"SMALL ROCKS PASSING DOCK SIDE TODAY",
	"HEAT LIMITS RAISED ON LOWER DECKS",
	"LAB DECK ASKS: WHO TOOK THE BEAKER?",
	"SHIPYARD ADDS A FIFTH BERTH",
	"HIRING HALL: 40 HAULERS WANTED",
	"WANTED: SOMEONE WHO CAN FIX LIFT B",
	"OUTER RING BUS LATE, AS ALWAYS",
	"JUMP GATE QUEUE: 3 HOURS",
	"JUMP GATE QUEUE: 5 MINUTES. WHY?",
	"MARKET OPENS LATE, KEY LOST",
	"LOST: ONE HAULER, BIG, RED, BEEPS",
	"FOUND: BLIP. BLIP IS FINE.",
	"BLIP SEEN AGAIN NEAR DOCK 3",
	"SWARM STAYS AWAY. NOBODY KNOWS WHY",
	"SWARM CLOSES 2 ROUTES TO THE CORE",
	"HELLBENDER LAST SEEN HEADING DEEP",
	"BOUNTY DESK OPEN UNTIL LATE",
	"STATION CHOIR CANCELS, TOO LOUD",
	"HULL BALL FINAL SOLD OUT",
	"DECKS WIN HULL BALL ON THE LAST JUMP",
	"NEW STAR NAMED AFTER A DOCK CLERK",
	"AIR FILTERS CHANGED, PLEASE SNIFF",
	"SPIN DECK GRAVITY OFF FOR AN HOUR",
	"TEA SPILL FLOATING ON DECK 6, DUCK",
	"HEAT SINK PRICES AT A 9 YEAR HIGH",
	"COLD SNAP: HULLS CREAK ALL NIGHT",
	"DOCK FEES UNCHANGED, FOR ONCE",
	"DOCK FEES UP. OF COURSE THEY ARE.",
	"NO NEWS TODAY. GOOD NEWS.",
	"TRAFFIC: HEAVY ON THE INNER LANE",
	"HAULER CONVOY LEAVES AT NOON",
	"WRECK FOUND. IT WAS A BIG ROCK.",
	"SALVAGE TEAM FINDS A WORKING TOASTER",
	"TOASTER OWNER SAYS: THAT IS MINE",
	"CABIN FEVER CLINIC OPENS ON DECK 8",
	"LIBRARY ON DECK 1 HAS ONE BOOK",
	"ONE BOOK STILL OUT ON LOAN",
	"SCHOOL TRIP TO THE REACTOR, AGAIN",
	"REACTOR SAYS HI TO THE SCHOOL",
	"NEW COOK AT THE DECK 4 NOODLE CART",
	"LAYER 3 LIGHTS UP, LAYER 4 NOT YET",
	"NIGHT SHIFT GETS NEW CHAIRS",
	"CYGNET DRONE ASKS FOR A DAY OFF",
	"SOLARI REACTOR WINS HOTTEST AWARD",
	"KORVAN: IT FIRES. EVERY TIME.",
	"CALYX HULL GROWS AN EXTRA DOOR",
	"REDLINE SHOP MOVES, NO NEW ADDRESS",
	"VERITY WAIT LIST NOW 41 YEARS",
	"PROBATE COMBINE: EVEN YOU, ONE DAY",
	"SCRUB DRONES ON STRIKE FOR SOAP",
	"SOAP SHIPMENT DUE TUESDAY",
	"HAULER OF THE WEEK: THE SLOW PIGEON",
	"PIGEON NOT A REAL BIRD, SAYS OWNER",
	"STATION CLOCK FIXED, 3 MINUTES SLOW",
	"WARM SPELL IN THE OUTER RING",
	"THE SUN: STILL THERE",
	"JUMP SICKNESS UP 10% THIS SEASON",
	"ICE PRICES MELT",
	"RING ICE HARVEST BEST IN 5 YEARS",
	"DOCKS ASK PILOTS: PLEASE STOP HONKING",
	"THERE IS NO HONKING IN SPACE",
	"COUPLING PRICES UP 6%",
	"SCRAP METAL DOWN 3%",
	"COOLANT SPOT PRICE: 14 CR",
	"DRONE TAX VOTE PUT OFF AGAIN",
	"NEW RULE: ONE PET ROCK PER CABIN",
	"PET ROCK OWNERS MARCH ON DECK 2",
	"DOCK 3 WINS CLEANEST DOCK",
	"DOCK 3 WINS DIRTIEST DOCK, TOO",
	"LOST AND FOUND FULL. STOP LOSING.",
	"FOUND: 400 RECALLED COUPLINGS",
	"RESCUE TUG BACK WITH 2 HAULERS",
	"HEAT STORM DUE NEAR THE CORE",
	"MOST USED SHIP NAME: BOAT, AGAIN",
	"PAINT SHOP RUNS OUT OF GREY",
	"GREY BACK IN STOCK",
	"OLD DOCK 11 TO BECOME A GARDEN",
	"GARDEN TO BECOME DOCK 11 AGAIN",
	"SIGNAL LOST NEAR THE DEEP LAYERS",
	"SIGNAL FOUND. IT WAS A RADIO.",
	"PEN PAL CLUB HITS 1,000 LETTERS",
	"JUMP INSURANCE CLAIMS: STILL ZERO",
	"NEW SHIP SMELL NOW SOLD IN A CAN",
	"BIG CRATE, SMALL DOOR: DOCK 5 STUCK",
	"CRATE FREED. DOOR NOT.",
	"STATION BAND PLAYS FRIDAY, DECK 6",
	"MOON ROCK UP, MOON DUST DOWN",
	"FOG IN HOLD 2 IS JUST STEAM",
	"SHORT JUMPS ONLY, SAYS GATE CREW",
	"BIG HAUL DOCKS, CROWD CHEERS",
	"HULL WAX NOW 3 FOR 1",
	"SCRAP TIDE ENDS AT DOCK 12",
	"EXTRA LIGHT HOURS ON DECK 1",
	"WIND TODAY: NONE. AS ALWAYS.",
	"OUTSIDE: 3 KELVIN. WRAP UP WARM.",
	"SNACK BOX ON DECK 2 EATS COINS",
	"FOUND IN SNACK BOX: 400 COINS",
	"SHIPYARD WAIT DOWN TO 2 DAYS",
	"HEAT VENTS OPEN ON THE HOUR",
	"LONGEST HAUL: 61 DAYS, 1 SANDWICH",
	"SWARM SIGHTINGS DOWN THIS WEEK",
	"SWARM SIGHTINGS UP. SORRY.",
	"DOCK 1 PAINTED. SAME COLOUR.",
	"SPACE WALK CLUB: ALL BACK SAFE",
	"LIFT B FIXED. LIFT A BROKEN.",
	"QUIET HOURS: PLEASE JUMP SOFTLY",
	"HAULER SINGS AT DOCK, FINED 2 CR",
	"COMET OVERHEAD TONIGHT, WAVE AT IT",
	"LOST: GRANDMA'S WELDER. SHE IS CROSS",
	"TODAY'S STARS: SAME AS YESTERDAY",
]

## Other people's listings on the marketplace: what they want done.
const DECOYS := ["HAUL 3 CRATES", "SCRAP RUN", "ESCORT, ONE JUMP", "FIX MY DRONE", "COOLANT, CHEAP",
	"CREW WANTED", "LOST CARGO", "DOCK SWEEP", "TOW, NO QUESTIONS", "SPARE COILS",
	"HAUL 1 BIG CRATE", "MOVE MY BUNK", "WALK MY DRONE", "SCRUB MY HULL", "TOW A WRECK",
	"OLD HULL WAX, OPEN", "SPARE FUEL CELLS", "PILOT FOR HIRE", "NEED A WELDER", "BUY MY COUPLINGS",
	"GRAV BOOT, LEFT", "GRAV BOOT, RIGHT", "FIX MY HEATER", "NAV CHART, OLD", "COOK FOR CREW",
	"CARRY MY MAIL", "HAUL ICE TO DOCK 2", "SCRAP, BY THE TON", "WANTED: SPARE AIR", "CREW BUNK FOR RENT",
	"ESCORT TO THE RING", "FIND MY CAT", "PET ROCK, GOOD HOME", "SPACE SUIT, AS NEW", "SUIT, ONE HOLE",
	"DRONE PARTS, MIXED", "WIRE, 40 METRES", "OLD REACTOR, WARM", "COOLANT, HALF FULL", "HEAT SINK, USED",
	"HAUL MY PIANO", "PIANO, BENT", "PAINT MY SHIP NAME", "MIND MY DRONE", "LEARN TO JUMP, 1 HR",
	"SALVAGE PARTNER", "RIDE TO DOCK 9", "DOCK SPOT, SHARED", "SWAP BUNKS, DECK 5", "WATCH MY SHIP 1 HR",
	"NOODLE RUN, DECK 3", "FIX MY AIRLOCK", "AIRLOCK, NEEDS FIX", "LOST: ONE SOCK", "FOUND: ONE SOCK",
	"HULL PLATES, 6", "WINDOW, ROUND", "WINDOW, CRACKED", "CARRY 2 TANKS", "HAUL SCRAP OUT",
	"CLEAN MY VENTS", "PAINT MY HULL RED", "RED PAINT, 1 CAN", "SPARE SEAT, NO JUMP", "JUMP BUDDY WANTED",
	"BUY MY WRECK", "WRECK, GOOD BONES", "TOW, ONE WAY", "MOVE 40 BOXES", "BOXES, EMPTY",
	"DRONE, BARELY USED", "DRONE, VERY USED", "TEACH MY DRONE", "SCRAP RUN, LAYER 2", "SCOUT THE RING",
	"HELLBENDER TIPS?", "SWARM MAPS, OLD", "COLD SLEEP POD", "POD, SLIGHTLY WARM", "COOK, NO NOODLES",
	"NOODLES, BULK", "CARGO NET, BIG", "HAUL FOOD, DECK 8", "RENT MY HOLD", "HOLD SPACE, 2 TONS",
	"FUEL, CHEAP, ASK", "LAMP, SPACE GRADE", "BENCH SEAT, BENT", "WELDER, NO GLOVES", "GLOVES, NO WELDER",
	"SPARE COUPLING", "MEND MY SUIT", "SUIT REPAIR, FAST", "PRESS MY UNIFORM", "TRADE TEA FOR AIR",
	"PEN PAL WANTED", "WRITE MY LETTER", "READ TO MY DRONE", "ASTEROID, SMALL", "ROCK, NOT A PET",
	"FOUND: SHIP KEY", "LOST: SHIP KEY", "STAR CHART, NEW", "CALYX MOSS CUTTING", "SOLARI PLATE, HOT",
	"KORVAN SHELLS, 20", "CYGNET DRONE, SHY", "REDLINE PARTS, ASK", "VERITY SEAT, SIGNED", "PROBATE SCRAP LOT",
	"DOCK SWEEP, NIGHT", "GUARD MY CRATES", "QUEUE FOR ME", "HOLD MY GATE SPOT", "FIX MY LIFT",
	"COUNT MY BOLTS", "BOLTS, UNCOUNTED", "HAUL WATER", "WATER, MOSTLY", "MOVE MY MOTHER",
	"HAUL AN ENGINE", "ENGINE, NO SHIP", "SHIP, NO ENGINE", "SPARE BUNK BED", "MATTRESS, FLAT",
	"TAKE MY MATTRESS", "VENT MY HEAT", "HEAT, FREE TO TAKE", "BUY MY HEAT", "BOUNTY HELP, SPLIT",
	"SPLIT A JUMP", "SHARE A TOW", "TOW ME HOME", "ESCORT, NO SINGING", "QUIET PILOT",
	"PILOT, LOUD", "CREW, ANY", "COOK WANTED, FAST", "DECK 6 PARTY HELP", "CHAIRS, 30",
	"TABLE, ROUND", "DRONE LEGS, SCRAP", "ROBOT ARM, LEFT", "ARM, WAVES ONLY", "OLD RADIO, WORKS",
	"RADIO, NO SOUND", "TUNE MY REACTOR", "MY REACTOR HUMS", "FIND MY CREW", "LOST CREW, 2",
	"CRATE OF BOLTS", "SECRET CRATE", "DO NOT OPEN CRATE", "OPEN THIS CRATE", "SMALL JOB, BIG PAY",
	"BIG JOB, SMALL PAY", "QUICK JUMP, 2 CR", "HAUL SOIL TO CALYX", "SOIL, 3 BAGS", "PLANT, ALIVE",
	"PLANT, MOSTLY ALIVE", "WATER MY PLANT", "WALK THE DOCK DOG", "DOCK DOG, FRIENDLY", "HELMET, SMALL",
	"HELMET, FOGGY", "WIPE MY VISOR", "TOY SHIP, KORVAN", "HULL WAX, 1 TIN", "SCRAP, CLEAN",
	"SCRAP, DIRTY", "FIX MY CLOCK", "CLOCK, FAST", "ICE, 2 TONS", "HAUL ICE QUIETLY",
	"CHART THE LAYERS", "DIVE TO LAYER 4", "SALVAGE DIVE, DEEP", "WRECK WATCH, NIGHT", "GET MY DRONE BACK",
	"SWARM CLEANUP", "SCRUB SWARM GOO", "SHRED OLD FILES", "FILE MY FORMS", "SIGN FOR A CRATE",
	"TAKE MY SHIFT", "SHIFT SWAP, DECK 4", "SPARE HANDS, 1 DAY", "LIFT 3 TANKS", "PUSH MY HAULER",
	"JUMP START MY SHIP", "CABLES, LONG", "CABLE, SHORT", "MAP TO DOCK 7", "DOCK 7 PASS",
	"EARLY DOCK SLOT", "LATE DOCK SLOT", "HAUL A BATHTUB", "BATHTUB, NO TUB", "TEACH ME TO WELD"]
const STAMPS := ["SOLD", "PENDING", "EXPIRED", "SOLD", "TAKEN",
	"SOLD", "GONE", "RESERVED", "SOLD", "CLAIMED", "PENDING", "SOLD", "ON HOLD", "SOLD",
	"WITHDRAWN", "SOLD", "FLAGGED", "SOLD", "TAKEN", "SOLD OUT"]
